.\" Copyright (c) 2006 Henrik Brix Andersen <henrik@brixandersen.dk>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd July 17, 2007
.Dt WPA_PASSPHRASE 8
.Os
.Sh NAME
.Nm wpa_passphrase
.Nd "utility for generating a 256-bit pre-shared WPA key from an ASCII passphrase"
.Sh SYNOPSIS
.Nm
.Aq Ar ssid
.Op Ar passphrase
.Sh DESCRIPTION
The
.Nm
utility is a small program for generating a 256-bit pre-shared WPA key
from an ASCII passphrase and a given SSID. The output is formatted for
inclusion in
.Xr wpa_supplicant.conf 5 .
.Pp
If
.Nm
is called with only an SSID as argument it will prompt for a
passphrase on standard input.
.Sh SEE ALSO
.Xr wpa_supplicant.conf 5 ,
.Xr wpa_supplicant 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 6.3 .
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Jouni Malinen Aq Mt j@w1.fi .
.Pp
This manual page was written by
.An Henrik Brix Andersen Aq Mt henrik@brixandersen.dk .
