# Fail on warnings - also for files referenced in subdirs
# -Werror can be disabled for specific files using:
# CFLAGS_<file.o> := -Wno-error
subdir-ccflags-y := -Werror


# mips object files
# The object files are linked as core-y files would be linked

obj-y += kernel/
obj-y += mm/
obj-y += math-emu/
