.\"
.\" Copyright (c) 2001 Jonathan Lemon <jlemon@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd April 14, 2011
.Dt CONSCONTROL 8
.Os
.Sh NAME
.Nm conscontrol
.Nd control physical console devices
.Sh SYNOPSIS
.Nm
.Op Cm list
.Nm
.Cm mute on | off
.Nm
.Cm add | delete
.Ar console
.Nm
.Cm set | unset Ar console
.Sh DESCRIPTION
The
.Nm
utility is used to examine and modify the physical devices which back
the virtual console devices.
If no arguments
(or only the
.Cm list
command)
are specified,
the current console settings are shown.
.Pp
There are two types of logical consoles; a high level console which
is represented by
.Pa /dev/console ,
and a low level console.
The low level console is used for kernel
.Xr printf 9
and
.Xr ddb 4
debugger support,
while the high level console is used by user programs like
.Xr syslogd 8 .
Multiple device support is implemented only for the low level console;
the high level console is set to the first device in the console list.
.Pp
Multiple console support may be invoked by passing the kernel the
.Fl D
flag from the boot loader, or by using
.Nm
to change the list of console devices after the system has booted.
.Pp
The following options are available:
.Bl -tag -width indent
.It Cm add | delete Ar console
Add or delete a physical device from the logical console.
The device must support low-level console operations.
Adding a device will place it at the front of the list of console
devices; the first device is used for the high level console.
.Pp
The
.Ar console
argument
is the name of a console device in
.Pa /dev ;
the name of the directory may be omitted.
.It Cm mute on | off
Change the state of console muting.
All console output is suppressed when console muting is
.Cm on .
.It Cm set | unset Ar console
Set or unset the virtual console.
When unset, output from the system, such as the kernel
.Xr printf 9 ,
always goes out to the real main console.
When set, it goes to another.
This is an interface to the tty ioctl
.Dv TIOCCONS .
.El
.Sh SEE ALSO
.Xr sio 4 ,
.Xr syscons 4 ,
.Xr tty 4 ,
.Xr vt 4 ,
.Xr boot 8 ,
.Xr loader 8
.Sh HISTORY
The
.Nm
utility first appeared in
.Fx 5.0 .
.Sh AUTHORS
.An Jonathan Lemon
