# gyroscope drivers

obj-$(CONFIG_GYRO_SENSOR_K3G) 	+= k3g.o
obj-$(CONFIG_GYRO_L3G4200D) 	+= l3g4200d.o
obj-$(CONFIG_GYRO_L3G20D) 	+= l3g20d.o
obj-$(CONFIG_GYRO_EWTSA) 	+= ewtsa.o
obj-$(CONFIG_GYRO_MPU6880)    += mpu6880_gyro.o