# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SPACEMIT_CCU)	+= spacemit-ccu.o
spacemit-ccu-y			+= ccu_common.o
spacemit-ccu-y			+= ccu_pll.o
spacemit-ccu-y			+= ccu_mix.o
spacemit-ccu-y			+= ccu_ddn.o

obj-$(CONFIG_SPACEMIT_K1_CCU)	+= spacemit-ccu-k1.o
spacemit-ccu-k1-y		+= ccu-k1.o

obj-$(CONFIG_SPACEMIT_K3_CCU)	+= spacemit-ccu-k3.o
spacemit-ccu-k3-y		+= ccu-k3.o
