#
# STMicroelectonics LIS3LV02D and similar accelerometers
#

obj-$(CONFIG_SENSORS_LIS3LV02D) += lis3lv02d.o
obj-$(CONFIG_SENSORS_LIS3_SPI)	+= lis3lv02d_spi.o
obj-$(CONFIG_SENSORS_LIS3_I2C)	+= lis3lv02d_i2c.o
