# SPDX-License-Identifier: GPL-2.0
snd-soc-simple-card-utils-objs	:= simple-card-utils.o
snd-soc-simple-card-objs	:= simple-card.o
snd-soc-audio-graph-card-objs	:= audio-graph-card.o
snd-soc-audio-graph-card2-objs	:= audio-graph-card2.o
snd-soc-audio-graph-card2-custom-sample-objs := audio-graph-card2-custom-sample.o
snd-soc-test-component-objs	:= test-component.o

obj-$(CONFIG_SND_SIMPLE_CARD_UTILS)	+= snd-soc-simple-card-utils.o
obj-$(CONFIG_SND_SIMPLE_CARD)		+= snd-soc-simple-card.o
obj-$(CONFIG_SND_AUDIO_GRAPH_CARD)	+= snd-soc-audio-graph-card.o
obj-$(CONFIG_SND_AUDIO_GRAPH_CARD2)	+= snd-soc-audio-graph-card2.o
obj-$(CONFIG_SND_AUDIO_GRAPH_CARD2_CUSTOM_SAMPLE) += snd-soc-audio-graph-card2-custom-sample.o
obj-$(CONFIG_SND_TEST_COMPONENT)	+= snd-soc-test-component.o
