/* $FreeBSD$ */
#ifndef __ISO_C_VISIBLE
#include <sys/cdefs.h>
#endif

/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `acosf' function. */
#define HAVE_ACOSF 1

/* Define to 1 if you have the `acosl' function. */
/* #undef HAVE_ACOSL */

/* Define to 1 if you have the `asinf' function. */
#define HAVE_ASINF 1

/* Define to 1 if you have the `asinl' function. */
/* #undef HAVE_ASINL */

/* Define to 1 if you have the `atan2f' function. */
#define HAVE_ATAN2F 1

/* Define to 1 if you have the `atan2l' function. */
#define HAVE_ATAN2L 1

/* Define to 1 if you have the `atanf' function. */
#define HAVE_ATANF 1

/* Define to 1 if you have the `atanl' function. */
#define HAVE_ATANL 1

/* Define to 1 if you have the `ceilf' function. */
#define HAVE_CEILF 1

/* Define to 1 if you have the `ceill' function. */
#define HAVE_CEILL 1

/* Define to 1 if you have the <complex.h> header file. */
#define HAVE_COMPLEX_H 1

/* Define to 1 if you have the `copysign' function. */
#define HAVE_COPYSIGN 1

/* Define to 1 if you have the `copysignf' function. */
#define HAVE_COPYSIGNF 1

/* Define to 1 if you have the `copysignl' function. */
#define HAVE_COPYSIGNL 1

/* Define to 1 if you have the `cosf' function. */
#define HAVE_COSF 1

/* Define to 1 if you have the `coshf' function. */
#define HAVE_COSHF 1

/* Define to 1 if you have the `coshl' function. */
#define HAVE_COSHL 1

/* Define to 1 if you have the `cosl' function. */
#define HAVE_COSL 1

/* Define to 1 if you have the <endian.h> header file. */
/* #undef HAVE_ENDIAN_H */

/* Define to 1 if you have the `expf' function. */
#define HAVE_EXPF 1

/* Define to 1 if you have the `expl' function. */
#define HAVE_EXPL 1

/* Define to 1 if you have the `fabsf' function. */
#define HAVE_FABSF 1

/* Define to 1 if you have the `fabsl' function. */
#define HAVE_FABSL 1

/* Define to 1 if you have the <fenv.h> header file. */
#define HAVE_FENV_H 1

/* Define to 1 if you have the `finite' function. */
#define HAVE_FINITE 1

/* Define to 1 if you have the `finitef' function. */
#define HAVE_FINITEF 1

/* Define to 1 if you have the `finitel' function. */
/* #undef HAVE_FINITEL */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `floorf' function. */
#define HAVE_FLOORF 1

/* Define to 1 if you have the `floorl' function. */
#define HAVE_FLOORL 1

/* Define to 1 if you have the `fmodf' function. */
#define HAVE_FMODF 1

/* Define to 1 if you have the `fmodl' function. */
#define HAVE_FMODL 1

/* Define to 1 if you have the `fpclass' function. */
/* #undef HAVE_FPCLASS */

/* Define to 1 if you have the <fp.h> header file. */
/* #undef HAVE_FP_H */

/* Define to 1 if you have the `frexpf' function. */
#define HAVE_FREXPF 1

/* Define to 1 if you have the `frexpl' function. */
#define HAVE_FREXPL 1

/* Define to 1 if you have the <gconv.h> header file. */
/* #undef HAVE_GCONV_H */

/* Define if _Unwind_GetIPInfo is available. */
#define HAVE_GETIPINFO 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define if gthr-default.h exists (meaning that threading support is
   enabled). */
#define HAVE_GTHR_DEFAULT 1

/* Define to 1 if you have the `hypot' function. */
#define HAVE_HYPOT 1

/* Define to 1 if you have the `hypotf' function. */
#define HAVE_HYPOTF 1

/* Define to 1 if you have the `hypotl' function. */
#define HAVE_HYPOTL 1

/* Define to 1 if you have the `iconv' function. */
#define HAVE_ICONV 1

/* Define to 1 if you have the `iconv_close' function. */
#define HAVE_ICONV_CLOSE 1

/* Define to 1 if you have the `iconv_open' function. */
#define HAVE_ICONV_OPEN 1

/* Define to 1 if you have the <ieeefp.h> header file. */
#define HAVE_IEEEFP_H 1

/* Define if int64_t is available in <stdint.h>. */
#define HAVE_INT64_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isinf' function. */
#define HAVE_ISINF 1

/* Define to 1 if you have the `isinff' function. */
/* #undef HAVE_ISINFF */

/* Define to 1 if you have the `isinfl' function. */
/* #undef HAVE_ISINFL */

/* Define to 1 if you have the `isnan' function. */
#define HAVE_ISNAN 1

/* Define to 1 if you have the `isnanf' function. */
#define HAVE_ISNANF 1

/* Define to 1 if you have the `isnanl' function. */
/* #undef HAVE_ISNANL */

/* Defined if iswblank exists. */
#define HAVE_ISWBLANK 1

/* Define if LC_MESSAGES is available in <locale.h>. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the `ldexpf' function. */
#define HAVE_LDEXPF 1

/* Define to 1 if you have the `ldexpl' function. */
#define HAVE_LDEXPL 1

/* Define to 1 if you have the <libintl.h> header file. */
/* #undef HAVE_LIBINTL_H */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Only used in build directory testsuite_hooks.h. */
#define HAVE_LIMIT_AS 1

/* Only used in build directory testsuite_hooks.h. */
#define HAVE_LIMIT_DATA 1

/* Only used in build directory testsuite_hooks.h. */
#define HAVE_LIMIT_FSIZE 1

/* Only used in build directory testsuite_hooks.h. */
#define HAVE_LIMIT_RSS 1

/* Only used in build directory testsuite_hooks.h. */
#define HAVE_LIMIT_VMEM 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the `log10f' function. */
#define HAVE_LOG10F 1

/* Define to 1 if you have the `log10l' function. */
#define HAVE_LOG10L 1

/* Define to 1 if you have the `logf' function. */
#define HAVE_LOGF 1

/* Define to 1 if you have the `logl' function. */
#define HAVE_LOGL 1

/* Define to 1 if you have the <machine/endian.h> header file. */
#define HAVE_MACHINE_ENDIAN_H 1

/* Define to 1 if you have the <machine/param.h> header file. */
#define HAVE_MACHINE_PARAM_H 1

/* Define if mbstate_t exists in wchar.h. */
#define HAVE_MBSTATE_T 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `modf' function. */
#define HAVE_MODF 1

/* Define to 1 if you have the `modff' function. */
#define HAVE_MODFF 1

/* Define to 1 if you have the `modfl' function. */
#define HAVE_MODFL 1

/* Define to 1 if you have the <nan.h> header file. */
/* #undef HAVE_NAN_H */

/* Define to 1 if you have the `nl_langinfo' function. */
#define HAVE_NL_LANGINFO 1

/* Define if poll is available in <poll.h>. */
#define HAVE_POLL 1

/* Define to 1 if you have the `powf' function. */
#define HAVE_POWF 1

/* Define to 1 if you have the `powl' function. */
#define HAVE_POWL 1

/* Define to 1 if you have the `qfpclass' function. */
/* #undef HAVE_QFPCLASS */

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define if sigsetjmp is available. */
#define HAVE_SIGSETJMP 1

/* Define to 1 if you have the `sincos' function. */
#define HAVE_SINCOS 1

/* Define to 1 if you have the `sincosf' function. */
#define HAVE_SINCOSF 1

/* Define to 1 if you have the `sincosl' function. */
#define HAVE_SINCOSL 1

/* Define to 1 if you have the `sinf' function. */
#define HAVE_SINF 1

/* Define to 1 if you have the `sinhf' function. */
#define HAVE_SINHF 1

/* Define to 1 if you have the `sinhl' function. */
#define HAVE_SINHL 1

/* Define to 1 if you have the `sinl' function. */
#define HAVE_SINL 1

/* Define to 1 if you have the `sqrtf' function. */
#define HAVE_SQRTF 1

/* Define to 1 if you have the `sqrtl' function. */
#define HAVE_SQRTL 1

/* Define to 1 if you have the <stdbool.h> header file. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define if strerror_l is available in <string.h>. */
/* #undef HAVE_STRERROR_L */

/* Define if strerror_r is available in <string.h>. */
#define HAVE_STRERROR_R 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strtof' function. */
#define HAVE_STRTOF 1

/* Define to 1 if you have the `strtold' function. */
#define HAVE_STRTOLD 1

/* Define if strxfrm_l is available in <string.h>. */
#define HAVE_STRXFRM_L 1

/* Define to 1 if you have the <sys/filio.h> header file. */
#define HAVE_SYS_FILIO_H 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ipc.h> header file. */
#define HAVE_SYS_IPC_H 1

/* Define to 1 if you have the <sys/isa_defs.h> header file. */
/* #undef HAVE_SYS_ISA_DEFS_H */

/* Define to 1 if you have the <sys/machine.h> header file. */
/* #undef HAVE_SYS_MACHINE_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/sem.h> header file. */
#define HAVE_SYS_SEM_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define HAVE_SYS_UIO_H 1

/* Define if S_IFREG is available in <sys/stat.h>. */
#define HAVE_S_ISREG 1

/* Define to 1 if you have the `tanf' function. */
#define HAVE_TANF 1

/* Define to 1 if you have the `tanhf' function. */
#define HAVE_TANHF 1

/* Define to 1 if you have the `tanhl' function. */
#define HAVE_TANHL 1

/* Define to 1 if you have the `tanl' function. */
#define HAVE_TANL 1

/* Define to 1 if the target supports thread-local storage. */
#if !defined(__mips__)
#define HAVE_TLS 1
#endif

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

#if __ISO_C_VISIBLE >= 1999
/* Defined if vfwscanf exists. */
#define HAVE_VFWSCANF 1

/* Defined if vswscanf exists. */
#define HAVE_VSWSCANF 1

/* Defined if vwscanf exists. */
#define HAVE_VWSCANF 1
#endif /* __ISO_C_VISIBLE >= 1999 */

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

#if __ISO_C_VISIBLE >= 1999
/* Defined if wcstof exists. */
#define HAVE_WCSTOF 1
#endif /* __ISO_C_VISIBLE >= 1999 */

/* Define to 1 if you have the <wctype.h> header file. */
#define HAVE_WCTYPE_H 1

/* Define if writev is available in <sys/uio.h>. */
#define HAVE_WRITEV 1

/* Define to 1 if you have the `_acosf' function. */
/* #undef HAVE__ACOSF */

/* Define to 1 if you have the `_acosl' function. */
/* #undef HAVE__ACOSL */

/* Define to 1 if you have the `_asinf' function. */
/* #undef HAVE__ASINF */

/* Define to 1 if you have the `_asinl' function. */
/* #undef HAVE__ASINL */

/* Define to 1 if you have the `_atan2f' function. */
/* #undef HAVE__ATAN2F */

/* Define to 1 if you have the `_atan2l' function. */
/* #undef HAVE__ATAN2L */

/* Define to 1 if you have the `_atanf' function. */
/* #undef HAVE__ATANF */

/* Define to 1 if you have the `_atanl' function. */
/* #undef HAVE__ATANL */

/* Define to 1 if you have the `_ceilf' function. */
/* #undef HAVE__CEILF */

/* Define to 1 if you have the `_ceill' function. */
/* #undef HAVE__CEILL */

/* Define to 1 if you have the `_copysign' function. */
/* #undef HAVE__COPYSIGN */

/* Define to 1 if you have the `_copysignl' function. */
/* #undef HAVE__COPYSIGNL */

/* Define to 1 if you have the `_cosf' function. */
/* #undef HAVE__COSF */

/* Define to 1 if you have the `_coshf' function. */
/* #undef HAVE__COSHF */

/* Define to 1 if you have the `_coshl' function. */
/* #undef HAVE__COSHL */

/* Define to 1 if you have the `_cosl' function. */
/* #undef HAVE__COSL */

/* Define to 1 if you have the `_expf' function. */
/* #undef HAVE__EXPF */

/* Define to 1 if you have the `_expl' function. */
/* #undef HAVE__EXPL */

/* Define to 1 if you have the `_fabsf' function. */
/* #undef HAVE__FABSF */

/* Define to 1 if you have the `_fabsl' function. */
/* #undef HAVE__FABSL */

/* Define to 1 if you have the `_finite' function. */
/* #undef HAVE__FINITE */

/* Define to 1 if you have the `_finitef' function. */
/* #undef HAVE__FINITEF */

/* Define to 1 if you have the `_finitel' function. */
/* #undef HAVE__FINITEL */

/* Define to 1 if you have the `_floorf' function. */
/* #undef HAVE__FLOORF */

/* Define to 1 if you have the `_floorl' function. */
/* #undef HAVE__FLOORL */

/* Define to 1 if you have the `_fmodf' function. */
/* #undef HAVE__FMODF */

/* Define to 1 if you have the `_fmodl' function. */
/* #undef HAVE__FMODL */

/* Define to 1 if you have the `_fpclass' function. */
/* #undef HAVE__FPCLASS */

/* Define to 1 if you have the `_frexpf' function. */
/* #undef HAVE__FREXPF */

/* Define to 1 if you have the `_frexpl' function. */
/* #undef HAVE__FREXPL */

/* Define to 1 if you have the `_hypot' function. */
/* #undef HAVE__HYPOT */

/* Define to 1 if you have the `_hypotf' function. */
/* #undef HAVE__HYPOTF */

/* Define to 1 if you have the `_hypotl' function. */
/* #undef HAVE__HYPOTL */

/* Define to 1 if you have the `_isinf' function. */
/* #undef HAVE__ISINF */

/* Define to 1 if you have the `_isinff' function. */
/* #undef HAVE__ISINFF */

/* Define to 1 if you have the `_isinfl' function. */
/* #undef HAVE__ISINFL */

/* Define to 1 if you have the `_isnan' function. */
/* #undef HAVE__ISNAN */

/* Define to 1 if you have the `_isnanf' function. */
/* #undef HAVE__ISNANF */

/* Define to 1 if you have the `_isnanl' function. */
/* #undef HAVE__ISNANL */

/* Define to 1 if you have the `_ldexpf' function. */
/* #undef HAVE__LDEXPF */

/* Define to 1 if you have the `_ldexpl' function. */
/* #undef HAVE__LDEXPL */

/* Define to 1 if you have the `_log10f' function. */
/* #undef HAVE__LOG10F */

/* Define to 1 if you have the `_log10l' function. */
/* #undef HAVE__LOG10L */

/* Define to 1 if you have the `_logf' function. */
/* #undef HAVE__LOGF */

/* Define to 1 if you have the `_logl' function. */
/* #undef HAVE__LOGL */

/* Define to 1 if you have the `_modf' function. */
/* #undef HAVE__MODF */

/* Define to 1 if you have the `_modff' function. */
/* #undef HAVE__MODFF */

/* Define to 1 if you have the `_modfl' function. */
/* #undef HAVE__MODFL */

/* Define to 1 if you have the `_powf' function. */
/* #undef HAVE__POWF */

/* Define to 1 if you have the `_powl' function. */
/* #undef HAVE__POWL */

/* Define to 1 if you have the `_qfpclass' function. */
/* #undef HAVE__QFPCLASS */

/* Define to 1 if you have the `_sincos' function. */
/* #undef HAVE__SINCOS */

/* Define to 1 if you have the `_sincosf' function. */
/* #undef HAVE__SINCOSF */

/* Define to 1 if you have the `_sincosl' function. */
/* #undef HAVE__SINCOSL */

/* Define to 1 if you have the `_sinf' function. */
/* #undef HAVE__SINF */

/* Define to 1 if you have the `_sinhf' function. */
/* #undef HAVE__SINHF */

/* Define to 1 if you have the `_sinhl' function. */
/* #undef HAVE__SINHL */

/* Define to 1 if you have the `_sinl' function. */
/* #undef HAVE__SINL */

/* Define to 1 if you have the `_sqrtf' function. */
/* #undef HAVE__SQRTF */

/* Define to 1 if you have the `_sqrtl' function. */
/* #undef HAVE__SQRTL */

/* Define to 1 if you have the `_tanf' function. */
/* #undef HAVE__TANF */

/* Define to 1 if you have the `_tanhf' function. */
/* #undef HAVE__TANHF */

/* Define to 1 if you have the `_tanhl' function. */
/* #undef HAVE__TANHL */

/* Define to 1 if you have the `_tanl' function. */
/* #undef HAVE__TANL */

/* Define if the compiler/host combination has __builtin_abs. */
#define HAVE___BUILTIN_ABS 1

/* Define if the compiler/host combination has __builtin_cos. */
#define HAVE___BUILTIN_COS 1

/* Define if the compiler/host combination has __builtin_cosf. */
#define HAVE___BUILTIN_COSF 1

/* Define if the compiler/host combination has __builtin_cosl. */
#define HAVE___BUILTIN_COSL 1

/* Define if the compiler/host combination has __builtin_fabs. */
#define HAVE___BUILTIN_FABS 1

/* Define if the compiler/host combination has __builtin_fabsf. */
#define HAVE___BUILTIN_FABSF 1

/* Define if the compiler/host combination has __builtin_fabsl. */
#define HAVE___BUILTIN_FABSL 1

/* Define if the compiler/host combination has __builtin_labs. */
#define HAVE___BUILTIN_LABS 1

/* Define if the compiler/host combination has __builtin_sin. */
#define HAVE___BUILTIN_SIN 1

/* Define if the compiler/host combination has __builtin_sinf. */
#define HAVE___BUILTIN_SINF 1

/* Define if the compiler/host combination has __builtin_sinl. */
#define HAVE___BUILTIN_SINL 1

/* Define if the compiler/host combination has __builtin_sqrt. */
#define HAVE___BUILTIN_SQRT 1

/* Define if the compiler/host combination has __builtin_sqrtf. */
#define HAVE___BUILTIN_SQRTF 1

/* Define if the compiler/host combination has __builtin_sqrtl. */
#define HAVE___BUILTIN_SQRTL 1

/* Define to 1 if you have the `__signbit' function. */
#define HAVE___SIGNBIT 1

/* Define to 1 if you have the `__signbitf' function. */
#define HAVE___SIGNBITF 1

/* Define to 1 if you have the `__signbitl' function. */
#define HAVE___SIGNBITL 1

/* Name of package */
/* #undef PACKAGE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "package-unused"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "package-unused version-unused"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libstdc++"

/* Define to the version of this package. */
#define PACKAGE_VERSION "version-unused"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
/* #undef VERSION */

/* Define if builtin atomic operations are supported on this host. */
#if defined(__amd64__) || (defined(__i386__) && !defined(__tune_i386__))
#define _GLIBCXX_ATOMIC_BUILTINS 1
#endif

/* Define to use concept checking code from the boost libraries. */
/* #undef _GLIBCXX_CONCEPT_CHECKS */

/* Define if a fully dynamic basic_string is wanted. */
/* #undef _GLIBCXX_FULLY_DYNAMIC_STRING */

/* Define to 1 if a full hosted library is built, or 0 if freestanding. */
#define _GLIBCXX_HOSTED 1

/* Define if compatibility should be provided for -mlong-double-64. */
/* #undef _GLIBCXX_LONG_DOUBLE_COMPAT */

/* Define if ptrdiff_t is int. */
#if !defined(__LP64__)
#define _GLIBCXX_PTRDIFF_T_IS_INT 1
#endif

/* Define if using setrlimit to set resource limits during "make check" */
#define _GLIBCXX_RES_LIMITS 1

/* Define if size_t is unsigned int. */
#if !defined(__LP64__)
#define _GLIBCXX_SIZE_T_IS_UINT 1
#endif

/* Define if the compiler is configured for setjmp/longjmp exceptions. */
/* #undef _GLIBCXX_SJLJ_EXCEPTIONS */

/* Define to use symbol versioning in the shared library. */
#define _GLIBCXX_SYMVER 1

/* Define to use darwin versioning in the shared library. */
/* #undef _GLIBCXX_SYMVER_DARWIN */

/* Define to use GNU versioning in the shared library. */
#define _GLIBCXX_SYMVER_GNU 1

/* Define to use GNU namespace versioning in the shared library. */
/* #undef _GLIBCXX_SYMVER_GNU_NAMESPACE */

/* Define if C99 functions or macros from <wchar.h>, <math.h>, <complex.h>,
   <stdio.h>, and <stdlib.h> can be used or exposed. */
/* #undef _GLIBCXX_USE_C99 */

/* Define if C99 functions in <complex.h> should be used in <complex>. Using
   compiler builtins for these functions requires corresponding C99 library
   functions to be present. */
#define _GLIBCXX_USE_C99_COMPLEX 1

/* Define if C99 functions in <complex.h> should be used in <tr1/complex>.
   Using compiler builtins for these functions requires corresponding C99
   library functions to be present. */
/* #undef _GLIBCXX_USE_C99_COMPLEX_TR1 */

/* Define if C99 functions in <ctype.h> should be imported in <tr1/cctype> in
   namespace std::tr1. */
#define _GLIBCXX_USE_C99_CTYPE_TR1 1

/* Define if C99 functions in <fenv.h> should be imported in <tr1/cfenv> in
   namespace std::tr1. */
#define _GLIBCXX_USE_C99_FENV_TR1 1

/* Define if C99 functions in <inttypes.h> should be imported in
   <tr1/cinttypes> in namespace std::tr1. */
#define _GLIBCXX_USE_C99_INTTYPES_TR1 1

/* Define if C99 functions or macros in <math.h> should be imported in <cmath>
   in namespace std. */
#define _GLIBCXX_USE_C99_MATH 1

/* Define if C99 functions or macros in <math.h> should be imported in
   <tr1/cmath> in namespace std::tr1. */
/* #undef _GLIBCXX_USE_C99_MATH_TR1 */

/* Define if C99 types in <stdint.h> should be imported in <tr1/cstdint> in
   namespace std::tr1. */
#define _GLIBCXX_USE_C99_STDINT_TR1 1

/* Define if iconv and related functions exist and are usable. */
#define _GLIBCXX_USE_ICONV 1

/* Define if LFS support is available. */
/* #undef _GLIBCXX_USE_LFS */

/* Define if code specialized for long long should be used. */
#define _GLIBCXX_USE_LONG_LONG 1

/* Define if NLS translations are to be used. */
/* #undef _GLIBCXX_USE_NLS */

/* Define if dev/random and dev/urandom are available for the random_device of
   TR1 (Chapter 5.1). */
#define _GLIBCXX_USE_RANDOM_TR1 1

/* Define if code specialized for wchar_t should be used. */
#define _GLIBCXX_USE_WCHAR_T 1

#if defined (HAVE__ACOSF) && ! defined (HAVE_ACOSF)
# define HAVE_ACOSF 1
# define acosf _acosf
#endif

#if defined (HAVE__ACOSL) && ! defined (HAVE_ACOSL)
# define HAVE_ACOSL 1
# define acosl _acosl
#endif

#if defined (HAVE__ASINF) && ! defined (HAVE_ASINF)
# define HAVE_ASINF 1
# define asinf _asinf
#endif

#if defined (HAVE__ASINL) && ! defined (HAVE_ASINL)
# define HAVE_ASINL 1
# define asinl _asinl
#endif

#if defined (HAVE__ATAN2F) && ! defined (HAVE_ATAN2F)
# define HAVE_ATAN2F 1
# define atan2f _atan2f
#endif

#if defined (HAVE__ATAN2L) && ! defined (HAVE_ATAN2L)
# define HAVE_ATAN2L 1
# define atan2l _atan2l
#endif

#if defined (HAVE__ATANF) && ! defined (HAVE_ATANF)
# define HAVE_ATANF 1
# define atanf _atanf
#endif

#if defined (HAVE__ATANL) && ! defined (HAVE_ATANL)
# define HAVE_ATANL 1
# define atanl _atanl
#endif

#if defined (HAVE__CEILF) && ! defined (HAVE_CEILF)
# define HAVE_CEILF 1
# define ceilf _ceilf
#endif

#if defined (HAVE__CEILL) && ! defined (HAVE_CEILL)
# define HAVE_CEILL 1
# define ceill _ceill
#endif

#if defined (HAVE__COPYSIGN) && ! defined (HAVE_COPYSIGN)
# define HAVE_COPYSIGN 1
# define copysign _copysign
#endif

#if defined (HAVE__COPYSIGNL) && ! defined (HAVE_COPYSIGNL)
# define HAVE_COPYSIGNL 1
# define copysignl _copysignl
#endif

#if defined (HAVE__COSF) && ! defined (HAVE_COSF)
# define HAVE_COSF 1
# define cosf _cosf
#endif

#if defined (HAVE__COSHF) && ! defined (HAVE_COSHF)
# define HAVE_COSHF 1
# define coshf _coshf
#endif

#if defined (HAVE__COSHL) && ! defined (HAVE_COSHL)
# define HAVE_COSHL 1
# define coshl _coshl
#endif

#if defined (HAVE__COSL) && ! defined (HAVE_COSL)
# define HAVE_COSL 1
# define cosl _cosl
#endif

#if defined (HAVE__EXPF) && ! defined (HAVE_EXPF)
# define HAVE_EXPF 1
# define expf _expf
#endif

#if defined (HAVE__EXPL) && ! defined (HAVE_EXPL)
# define HAVE_EXPL 1
# define expl _expl
#endif

#if defined (HAVE__FABSF) && ! defined (HAVE_FABSF)
# define HAVE_FABSF 1
# define fabsf _fabsf
#endif

#if defined (HAVE__FABSL) && ! defined (HAVE_FABSL)
# define HAVE_FABSL 1
# define fabsl _fabsl
#endif

#if defined (HAVE__FINITE) && ! defined (HAVE_FINITE)
# define HAVE_FINITE 1
# define finite _finite
#endif

#if defined (HAVE__FINITEF) && ! defined (HAVE_FINITEF)
# define HAVE_FINITEF 1
# define finitef _finitef
#endif

#if defined (HAVE__FINITEL) && ! defined (HAVE_FINITEL)
# define HAVE_FINITEL 1
# define finitel _finitel
#endif

#if defined (HAVE__FLOORF) && ! defined (HAVE_FLOORF)
# define HAVE_FLOORF 1
# define floorf _floorf
#endif

#if defined (HAVE__FLOORL) && ! defined (HAVE_FLOORL)
# define HAVE_FLOORL 1
# define floorl _floorl
#endif

#if defined (HAVE__FMODF) && ! defined (HAVE_FMODF)
# define HAVE_FMODF 1
# define fmodf _fmodf
#endif

#if defined (HAVE__FMODL) && ! defined (HAVE_FMODL)
# define HAVE_FMODL 1
# define fmodl _fmodl
#endif

#if defined (HAVE__FPCLASS) && ! defined (HAVE_FPCLASS)
# define HAVE_FPCLASS 1
# define fpclass _fpclass
#endif

#if defined (HAVE__FREXPF) && ! defined (HAVE_FREXPF)
# define HAVE_FREXPF 1
# define frexpf _frexpf
#endif

#if defined (HAVE__FREXPL) && ! defined (HAVE_FREXPL)
# define HAVE_FREXPL 1
# define frexpl _frexpl
#endif

#if defined (HAVE__HYPOT) && ! defined (HAVE_HYPOT)
# define HAVE_HYPOT 1
# define hypot _hypot
#endif

#if defined (HAVE__HYPOTF) && ! defined (HAVE_HYPOTF)
# define HAVE_HYPOTF 1
# define hypotf _hypotf
#endif

#if defined (HAVE__HYPOTL) && ! defined (HAVE_HYPOTL)
# define HAVE_HYPOTL 1
# define hypotl _hypotl
#endif

#if defined (HAVE__ISINF) && ! defined (HAVE_ISINF)
# define HAVE_ISINF 1
# define isinf _isinf
#endif

#if defined (HAVE__ISINFF) && ! defined (HAVE_ISINFF)
# define HAVE_ISINFF 1
# define isinff _isinff
#endif

#if defined (HAVE__ISINFL) && ! defined (HAVE_ISINFL)
# define HAVE_ISINFL 1
# define isinfl _isinfl
#endif

#if defined (HAVE__ISNAN) && ! defined (HAVE_ISNAN)
# define HAVE_ISNAN 1
# define isnan _isnan
#endif

#if defined (HAVE__ISNANF) && ! defined (HAVE_ISNANF)
# define HAVE_ISNANF 1
# define isnanf _isnanf
#endif

#if defined (HAVE__ISNANL) && ! defined (HAVE_ISNANL)
# define HAVE_ISNANL 1
# define isnanl _isnanl
#endif

#if defined (HAVE__LDEXPF) && ! defined (HAVE_LDEXPF)
# define HAVE_LDEXPF 1
# define ldexpf _ldexpf
#endif

#if defined (HAVE__LDEXPL) && ! defined (HAVE_LDEXPL)
# define HAVE_LDEXPL 1
# define ldexpl _ldexpl
#endif

#if defined (HAVE__LOG10F) && ! defined (HAVE_LOG10F)
# define HAVE_LOG10F 1
# define log10f _log10f
#endif

#if defined (HAVE__LOG10L) && ! defined (HAVE_LOG10L)
# define HAVE_LOG10L 1
# define log10l _log10l
#endif

#if defined (HAVE__LOGF) && ! defined (HAVE_LOGF)
# define HAVE_LOGF 1
# define logf _logf
#endif

#if defined (HAVE__LOGL) && ! defined (HAVE_LOGL)
# define HAVE_LOGL 1
# define logl _logl
#endif

#if defined (HAVE__MODF) && ! defined (HAVE_MODF)
# define HAVE_MODF 1
# define modf _modf
#endif

#if defined (HAVE__MODFF) && ! defined (HAVE_MODFF)
# define HAVE_MODFF 1
# define modff _modff
#endif

#if defined (HAVE__MODFL) && ! defined (HAVE_MODFL)
# define HAVE_MODFL 1
# define modfl _modfl
#endif

#if defined (HAVE__POWF) && ! defined (HAVE_POWF)
# define HAVE_POWF 1
# define powf _powf
#endif

#if defined (HAVE__POWL) && ! defined (HAVE_POWL)
# define HAVE_POWL 1
# define powl _powl
#endif

#if defined (HAVE__QFPCLASS) && ! defined (HAVE_QFPCLASS)
# define HAVE_QFPCLASS 1
# define qfpclass _qfpclass
#endif

#if defined (HAVE__SINCOS) && ! defined (HAVE_SINCOS)
# define HAVE_SINCOS 1
# define sincos _sincos
#endif

#if defined (HAVE__SINCOSF) && ! defined (HAVE_SINCOSF)
# define HAVE_SINCOSF 1
# define sincosf _sincosf
#endif

#if defined (HAVE__SINCOSL) && ! defined (HAVE_SINCOSL)
# define HAVE_SINCOSL 1
# define sincosl _sincosl
#endif

#if defined (HAVE__SINF) && ! defined (HAVE_SINF)
# define HAVE_SINF 1
# define sinf _sinf
#endif

#if defined (HAVE__SINHF) && ! defined (HAVE_SINHF)
# define HAVE_SINHF 1
# define sinhf _sinhf
#endif

#if defined (HAVE__SINHL) && ! defined (HAVE_SINHL)
# define HAVE_SINHL 1
# define sinhl _sinhl
#endif

#if defined (HAVE__SINL) && ! defined (HAVE_SINL)
# define HAVE_SINL 1
# define sinl _sinl
#endif

#if defined (HAVE__SQRTF) && ! defined (HAVE_SQRTF)
# define HAVE_SQRTF 1
# define sqrtf _sqrtf
#endif

#if defined (HAVE__SQRTL) && ! defined (HAVE_SQRTL)
# define HAVE_SQRTL 1
# define sqrtl _sqrtl
#endif

#if defined (HAVE__STRTOF) && ! defined (HAVE_STRTOF)
# define HAVE_STRTOF 1
# define strtof _strtof
#endif

#if defined (HAVE__STRTOLD) && ! defined (HAVE_STRTOLD)
# define HAVE_STRTOLD 1
# define strtold _strtold
#endif

#if defined (HAVE__TANF) && ! defined (HAVE_TANF)
# define HAVE_TANF 1
# define tanf _tanf
#endif

#if defined (HAVE__TANHF) && ! defined (HAVE_TANHF)
# define HAVE_TANHF 1
# define tanhf _tanhf
#endif

#if defined (HAVE__TANHL) && ! defined (HAVE_TANHL)
# define HAVE_TANHL 1
# define tanhl _tanhl
#endif

#if defined (HAVE__TANL) && ! defined (HAVE_TANL)
# define HAVE_TANL 1
# define tanl _tanl
#endif
