.\"	$OpenBSD: ssio.4,v 1.4 2007/07/15 20:00:49 kettenis Exp $
.\"
.\" Copyright (c) 2007 Mark Kettenis <kettenis@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 15 2007 $
.Dt SSIO 4 hppa
.Os
.Sh NAME
.Nm ssio
.Nd National Semiconductor PC87560 Legacy IO
.Sh SYNOPSIS
.Cd "ssio* at pci?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the National Semiconductor PC87560 Legacy IO
chip on systems with PA-8500 and later 64-bit CPUs.
It configures the Programmable Interrupt Controllers integrated on the chip
to route interrupts for the integrated
.Xr ohci 4
USB controller (which appears as a separate PCI device).
.Pp
.Ox
provides support for the following devices:
.Pp
.Bl -tag -width 12n -offset indent -compact
.It Xr com 4
serial communications interface
.It Xr lpt 4
parallel port driver
.El
.Sh SEE ALSO
.Xr intro 4 ,
.Xr pci 4
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 4.2 .
