/* SPDX-License-Identifier: MIT */
/*
 * Copyright © 2025 Intel Corporation
 */

#ifndef __INTEL_CASF_REGS_H__
#define __INTEL_CASF_REGS_H__

#include "intel_display_reg_defs.h"

#define _SHARPNESS_CTL_A		0x682B0
#define _SHARPNESS_CTL_B		0x68AB0
#define SHARPNESS_CTL(pipe)		_MMIO_PIPE(pipe, _SHARPNESS_CTL_A, _SHARPNESS_CTL_B)
#define   FILTER_EN			REG_BIT(31)
#define   FILTER_STRENGTH_MASK		REG_GENMASK(15, 8)
#define   FILTER_STRENGTH(x)		REG_FIELD_PREP(FILTER_STRENGTH_MASK, (x))
#define   FILTER_SIZE_MASK		REG_GENMASK(1, 0)
#define   SHARPNESS_FILTER_SIZE_3X3	REG_FIELD_PREP(FILTER_SIZE_MASK, 0)
#define   SHARPNESS_FILTER_SIZE_5X5	REG_FIELD_PREP(FILTER_SIZE_MASK, 1)
#define   SHARPNESS_FILTER_SIZE_7X7	REG_FIELD_PREP(FILTER_SIZE_MASK, 2)

#endif /* __INTEL_CASF_REGS__ */
