#
# Joshua Henderson, <joshua.henderson@microchip.com>
# Copyright (C) 2015 Microchip Technology, Inc.  All rights reserved.
#
obj-y			:= init.o time.o config.o

obj-$(CONFIG_EARLY_PRINTK)	+= early_console.o      \
				   early_pin.o		\
				   early_clk.o
