#
# Makefile for the Linux Wireless network device drivers.
#
obj-y += wifi_sys/rkwifi_sys_iface.o
obj-$(CONFIG_RTL8192CU) += rtl8192cu/
obj-$(CONFIG_RTL8192DU) += rtl8192du/
obj-$(CONFIG_RTL8188EU)	+= rtl8188eu/
obj-$(CONFIG_RTL8723AU)	+= rtl8723au/
obj-$(CONFIG_RKWIFI)   += rkwifi/
obj-$(CONFIG_RDA5990) += rda5990/
obj-$(CONFIG_MT5931)  += mt5931/
obj-$(CONFIG_MT5931_MT6622)  += mt5931/
obj-$(CONFIG_RTL8723BS) += rtl8723bs/
#obj-$(CONFIG_MT7601)	+= mt7601/
obj-$(CONFIG_MTK_COMBO_WIFI)	+= combo_mt66xx/
obj-$(CONFIG_MTK_MT5931)	+= mt5931_kk/
