# SPDX-License-Identifier: GPL-2.0
# Nomadik family pin control drivers
obj-$(CONFIG_PINCTRL_ABX500)	+= pinctrl-abx500.o
obj-$(CONFIG_PINCTRL_AB8500)	+= pinctrl-ab8500.o
obj-$(CONFIG_PINCTRL_AB8505)	+= pinctrl-ab8505.o
obj-$(CONFIG_PINCTRL_NOMADIK)	+= pinctrl-yesmadik.o
obj-$(CONFIG_PINCTRL_STN8815)	+= pinctrl-yesmadik-stn8815.o
obj-$(CONFIG_PINCTRL_DB8500)	+= pinctrl-yesmadik-db8500.o
