#
# Common TXx9
#
obj-$(CONFIG_MACH_TX39XX)      += generic/
obj-$(CONFIG_MACH_TX49XX)      += generic/

#
# Toshiba JMR-TX3927 board
#
obj-$(CONFIG_TOSHIBA_JMR3927)  += jmr3927/

#
# Toshiba RBTX49XX boards
#
obj-$(CONFIG_TOSHIBA_RBTX4927) += rbtx4927/
obj-$(CONFIG_TOSHIBA_RBTX4938) += rbtx4938/
obj-$(CONFIG_TOSHIBA_RBTX4939) += rbtx4939/
