#
# Makefile for the linux kernel.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).

# Object file lists.

# Cpu revision
obj-$(CONFIG_NOMADIK_8815) += cpu-8815.o
