# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>
#

snd-opti92x-ad1848-y := opti92x-ad1848.o
snd-opti92x-cs4231-y := opti92x-cs4231.o
snd-opti93x-y := opti93x.o
snd-miro-y := miro.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_OPTI92X_AD1848) += snd-opti92x-ad1848.o
obj-$(CONFIG_SND_OPTI92X_CS4231) += snd-opti92x-cs4231.o
obj-$(CONFIG_SND_OPTI93X) += snd-opti93x.o
obj-$(CONFIG_SND_MIRO) += snd-miro.o
