# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MM81X) += mm81x_core.o

mm81x_core-y += core.o
mm81x_core-y += mac.o
mm81x_core-y += hw.o
mm81x_core-y += fw.o
mm81x_core-y += command.o
mm81x_core-y += ps.o
mm81x_core-y += skbq.o
mm81x_core-y += yaps_hw.o
mm81x_core-y += yaps.o
mm81x_core-y += rc.o
mm81x_core-y += mmrc.o

obj-$(CONFIG_MM81X_USB) += mm81x_usb.o
mm81x_usb-y += usb.o

obj-$(CONFIG_MM81X_SDIO) += mm81x_sdio.o
mm81x_sdio-y += sdio.o
