# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_MFD_RKX110_X120) += rkx110_x120.o
rkx110_x120-objs := \
	hal/cru_core.o \
	hal/cru_rkx110.o \
	hal/cru_rkx120.o \
	hal/cru_rkx111.o \
	hal/cru_rkx121.o \
	hal/pinctrl_rkx110_x120.o \
	pattern_gen.o \
	rkx110_combrxphy.o \
	rkx110_dsi_rx.o \
	rkx110_x120_core.o \
	rkx110_linktx.o \
	rkx110.o \
	rkx120.o \
	rkx120_combtxphy.o \
	rkx120_dsi_tx.o \
	rkx120_linkrx.o \
	serdes_combphy.o

obj-$(CONFIG_ROCKCHIP_SERDES_DRM_PANEL) += rkx110_x120_panel.o
