# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the HISILICON BMC GE network device drivers.
#

obj-$(CONFIG_HIBMCGE) += hibmcge.o

hibmcge-objs = hbg_main.o hbg_hw.o hbg_mdio.o hbg_irq.o hbg_txrx.o hbg_ethtool.o
