/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Automatically generated by rvgen kunit.
 * May need manual intervention for function prototypes that couldn't be
 * found (e.g. are in another file) or variables to be exported.
 */

#ifndef __SSSW_KUNIT_H
#define __SSSW_KUNIT_H

#if IS_ENABLED(CONFIG_RV_MONITORS_KUNIT_TEST)

#include <linux/rv.h>
#include <rv/kunit.h>

extern const struct rv_sssw_ops {
	struct rv_kunit_mon mon;
	void (*handle_sched_set_state)(void *data, struct task_struct *tsk, int state);
	void (*handle_sched_switch)(void *data, bool preempt,
				struct task_struct *prev,
				struct task_struct *next,
				unsigned int prev_state);
	void (*handle_sched_wakeup)(void *data, struct task_struct *p);
	void (*handle_signal_deliver)(void *data, int sig,
				   struct kernel_siginfo *info,
				   struct k_sigaction *ka);
} rv_sssw_ops;
#endif

#endif /* __SSSW_KUNIT_H */
