# SPDX-License-Identifier: GPL-2.0
# Sophgo Platform Support
obj-$(CONFIG_SND_SOC_CV1800B_TDM) += cv1800b-tdm.o
obj-$(CONFIG_SND_SOC_CV1800B_ADC_CODEC) += cv1800b-sound-adc.o
obj-$(CONFIG_SND_SOC_CV1800B_DAC_CODEC) += cv1800b-sound-dac.o
