$ $FreeBSD$
$
$ Message catalog for sk_SK.ISO8859-2 locale
$
$ strerror() support catalog
$
$set 1
$ EPERM
1 Operácia nie je povolená
$ ENOENT
2 Neexistujúci súbor alebo adresár
$ ESRCH
3 Proces neexistuje
$ EINTR
4 Systémové volanie preru¹ené
$ EIO
5 Chyba vstupu/výstupu
$ ENXIO
6 Zariadenie nie je nakonfigurované
$ E2BIG
7 Príli¹ dlhý zoznam argumentov
$ ENOEXEC
8 Chybný formát spusteného súboru
$ EBADF
9 Chybný deskriptor súboru
$ ECHILD
10 Neexistuje ¾iaden potomok procesu
$ EDEADLK
11 Bolo zabránené zablokovaniu prostriedku
$ ENOMEM
12 Nie je mo¾né prideli» pamä»
$ EACCES
13 Prístup odmietnutý
$ EFAULT
14 Chybná adresa
$ ENOTBLK
15 Vy¾adované blokové zariadenie
$ EBUSY
16 Zariadenie je pou¾ívané
$ EEXIST
17 Súbor existuje
$ EXDEV
18 Odkaz medzi zariadeniami
$ ENODEV
19 Operácia nie je zariadením podporovaná
$ ENOTDIR
20 Nie je adresár
$ EISDIR
21 Je adresár
$ EINVAL
22 Chybný argument
$ ENFILE
23 Priveµa otvorených súborov v systéme
$ EMFILE
24 Priveµa otvorených súborov
$ ENOTTY
25 Nevhodné ioctl pre dané zariadenie
$ ETXTBSY
26 Textový súbor je pou¾ívaný
$ EFBIG
27 Súbor je príli¹ veµký
$ ENOSPC
28 Na zariadení nie je voµné miesto
$ ESPIPE
29 Neprípustné nastavenie pozície
$ EROFS
30 Súborový systém je len na èítanie
$ EMLINK
31 Priveµa odkazov
$ EPIPE
32 Preru¹ená rúra
$ EDOM
33 Èíselný argument mimo definièný obor
$ ERANGE
34 Výsledok príli¹ veµký alebo príli¹ malý
$ EAGAIN, EWOULDBLOCK
35 Zdroj je doèasne nedostupný
$ EINPROGRESS
36 Operácia práve prebieha
$ EALREADY
37 Operácia u¾ prebieha
$ ENOTSOCK
38 Socketová operácia na objekte, ktorý nie je socket
$ EDESTADDRREQ
39 Vy¾adovaná cieµová adresa
$ EMSGSIZE
40 Príli¹ dlhá správa
$ EPROTOTYPE
41 Protokol nie je socketom podporovaný
$ ENOPROTOOPT
42 Protokol nie je k dispozícii
$ EPROTONOSUPPORT
43 Protokol nie je podporovaný
$ ESOCKTNOSUPPORT
44 Typ socketu nie je podporovaný
$ EOPNOTSUPP
45 Operácia nie je podporovaná
$ EPFNOSUPPORT
46 Rodina protokolov nie je podporovaná
$ EAFNOSUPPORT
47 Rodina adries nie je podporovaná rodinou protokolov
$ EADDRINUSE
48 Adresa je u¾ pou¾ívaná
$ EADDRNOTAVAIL
49 Nie je mo¾né prideli» po¾adovanú adresu
$ ENETDOWN
50 Sie» je nefunkèná
$ ENETUNREACH
51 Sie» je nedostupná
$ ENETRESET
52 Sie» zru¹ila spojenie po resete
$ ECONNABORTED
53 Program spôsobil ukonèenie spojenia
$ ECONNRESET
54 Spojenie zru¹ené druhou stranou
$ ENOBUFS
55 Vyrovnávacia pamä» nie je k dispozícii
$ EISCONN
56 Socket je u¾ pripojený
$ ENOTCONN
57 Socket nie je pripojený
$ ESHUTDOWN
58 Nie je mo¾né posiela» po uzavretí socketu
$ ETOOMANYREFS
59 Príli¹ mnoho odkazov: nie je mo¾né spoji»
$ ETIMEDOUT
60 Èasový limit pre spojenie vypr¹al
$ ECONNREFUSED
61 Spojenie odmietnuté
$ ELOOP
62 Priveµa úrovní symbolických odkazov
$ ENAMETOOLONG
63 Meno súboru príli¹ dlhé
$ EHOSTDOWN
64 Vzdialený uzol je odpojený
$ EHOSTUNREACH
65 Neexistuje cesta k vzdialenému uzlu
$ ENOTEMPTY
66 Adresár nie je prázdny
$ EPROCLIM
67 Priveµa procesov
$ EUSERS
68 Priveµa pou¾ívateµov
$ EDQUOT
69 Disková kvóta prekroèená
$ ESTALE
70 Zastaralý NFS súborový ukazateµ
$ EREMOTE
71 Priveµa úrovní vzdialeného v ceste
$ EBADRPC
72 RPC ¹truktúra je chybná
$ ERPCMISMATCH
73 Chybná verzia RPC
$ EPROGUNAVAIL
74 RPC program nie je k dispozícii
$ EPROGMISMATCH
75 Chybná verzia RPC programu
$ EPROCUNAVAIL
76 Chybná RPC procedúra pre program
$ ENOLCK
77 Zámky nie sú k dispozícii
$ ENOSYS
78 Funkcia nie je implementovaná
$ EFTYPE
79 Nevhodný typ alebo formát súboru
$ EAUTH
80 Overenie práv neúspe¹né
$ ENEEDAUTH
81 Vy¾adovaný overovací objekt
$ EIDRM
82 Identifikátor odstránený
$ ENOMSG
83 Neexistuje správa ¾elaného typu
$ EOVERFLOW
84 Hodnota je pre daný dátový typ priveµká
$ EILSEQ
85 Neprípustná postupnos» bajtov
$ ENOTSUP
86 Nie je podporované
$ ECANCELED
87 Operácia zru¹ená
$ EBADMSG
88 Chybná alebo poru¹ená správa
$ ENODATA
89 ®iadna správa nie je k dispozícii
$ ENOSR
90 ®iadne STREAM zdroje
$ ENOSTR
91 Nie je STREAM
$ ETIME
92 Èasový limit pre STREAM ioctl vypr¹al
$ ENOATTR
93 Atribút nenájdený
$ EMULTIHOP
94 Pokus o spojenie cez viacero uzlov
$ ENOLINK
95 Odkaz bol pretrhnutý
$ EPROTO
96 Chyba protokolu
$
$ strsignal() support catalog
$
$set 2
$ SIGHUP
1 Terminál odpojený
$ SIGINT
2 Preru¹enie
$ SIGQUIT
3 Koniec
$ SIGILL
4 Chybná in¹trukcia
$ SIGTRAP
5 Trasovacia/ladiaca in¹trukcia
$ SIGABRT
6 Násilné ukonèenie
$ SIGEMT
7 Emulovaná in¹trukcia
$ SIGFPE
8 Výnimka pohyblivej rádovej èiarky
$ SIGKILL
9 Zabité
$ SIGBUS
10 Chyba na zbernici
$ SIGSEGV
11 Chyba segmentácie
$ SIGSYS
12 Chybné systémové volanie
$ SIGPIPE
13 Preru¹ená rúra
$ SIGALRM
14 Budík
$ SIGTERM
15 Ukonèené
$ SIGURG
16 Naliehavý vstupný/výstupný stav
$ SIGSTOP
17 Pozastavené (signál)
$ SIGTSTP
18 Pozastavené
$ SIGCONT
19 Pokraèovanie
$ SIGCHLD
20 Potomok procesu ukonèený
$ SIGTTIN
21 Pozastavené (terminálový vstup)
$ SIGTTOU
22 Pozastavené (terminálový výstup)
$ SIGIO
23 Vstup/výstup mo¾ný
$ SIGXCPU
24 Prekroèený èasový limit pre procesor
$ SIGXFSZ
25 Prekroèený limit veµkosti súboru
$ SIGVTALRM
26 Vypr¹al virtuálny èasovaè
$ SIGPROF
27 Vypr¹al profilovací èasovaè
$ SIGWINCH
28 Veµkos» okna zmenená
$ SIGINFO
29 ®iados» o informáciu
$ SIGUSR1
30 Pou¾ívateµom definovaný signál 1
$ SIGUSR2
31 Pou¾ívateµom definovaný signál 2
$ SIGPWR
32 Zlyhanie/opakované spustenie napájania
