#
#  Copyright 2000, 2001, 2008 MontaVista Software Inc.
#  Author: MontaVista Software, Inc. <source@mvista.com>
#
# Makefile for the Alchemy Semiconductor Pb1100 board.
#

obj-y := board_setup.o platform.o
