# SPDX-License-Identifier: (GPL-2.0-only OR BSD-3-Clause)
snd-sof-starfive-objs := jh7110-dsp.o

snd-sof-starfive-common-objs := starfive-common.o

obj-$(CONFIG_SND_SOC_SOF_STARFIVE) += snd-sof-starfive.o
obj-$(CONFIG_SND_SOC_SOF_STARFIVE_COMMON) += snd-sof-starfive-common.o
obj-$(CONFIG_STARFIVE_DSP)		+= jh7110-dsp-ipc.o
