# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_SYSFB_HELPER)	+= drm_sysfb_helper.o

obj-$(CONFIG_DRM_EFIDRM)	+= efidrm.o
obj-$(CONFIG_DRM_OFDRM)		+= ofdrm.o
obj-$(CONFIG_DRM_SIMPLEDRM)	+= simpledrm.o
obj-$(CONFIG_DRM_VESADRM)	+= vesadrm.o
