.\"	$OpenBSD: apliic.4,v 1.2 2021/12/24 07:05:55 jmc Exp $
.\"
.\" Copyright (c) 2021 Patrick Wildt <patrick@blueri.se>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 24 2021 $
.Dt APLIIC 4 arm64
.Os
.Sh NAME
.Nm apliic
.Nd Apple I2C controller
.Sh SYNOPSIS
.Cd "apliic* at fdt?"
.Cd "iic* at apliic?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the I2C controller found on various Apple SoCs.
.Sh SEE ALSO
.Xr iic 4 ,
.Xr intro 4
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 7.1 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Patrick Wildt Aq Mt patrick@blueri.se .
