
header-y := ip_conntrack_helper.h ip_conntrack_helper_h323_asn1.h	\
	    ip_conntrack_helper_h323_types.h ip_conntrack_protocol.h	\
	    ip_conntrack_sctp.h ip_conntrack_tcp.h ip_conntrack_tftp.h	\
	    ip_nat_pptp.h ipt_addrtype.h ipt_ah.h	\
	    ipt_CLASSIFY.h ipt_CLUSTERIP.h ipt_comment.h		\
	    ipt_connbytes.h ipt_connmark.h ipt_CONNMARK.h		\
	    ipt_conntrack.h ipt_dccp.h ipt_dscp.h ipt_DSCP.h ipt_ecn.h	\
	    ipt_ECN.h ipt_esp.h ipt_hashlimit.h ipt_helper.h		\
	    ipt_iprange.h ipt_length.h ipt_limit.h ipt_LOG.h ipt_mac.h	\
	    ipt_mark.h ipt_MARK.h ipt_multiport.h ipt_NFQUEUE.h		\
	    ipt_owner.h ipt_physdev.h ipt_pkttype.h ipt_policy.h	\
	    ipt_realm.h ipt_recent.h ipt_REJECT.h ipt_SAME.h		\
	    ipt_sctp.h ipt_state.h ipt_string.h ipt_tcpmss.h		\
	    ipt_TCPMSS.h ipt_tos.h ipt_TOS.h ipt_ttl.h ipt_TTL.h	\
	    ipt_ULOG.h

unifdef-y := ip_conntrack.h ip_conntrack_h323.h ip_conntrack_irc.h	\
	ip_conntrack_pptp.h ip_conntrack_proto_gre.h			\
	ip_conntrack_tuple.h ip_nat.h ip_nat_rule.h ip_queue.h		\
	ip_tables.h
