# $FreeBSD$

PACKAGE=	tests

TAP_TESTS_SH=	legacy_test

${PACKAGE}FILES+=		regress.b.out
${PACKAGE}FILES+=		regress.bwidth.out
${PACKAGE}FILES+=		regress.d.out
${PACKAGE}FILES+=		regress.f.out
${PACKAGE}FILES+=		regress.l1.out
${PACKAGE}FILES+=		regress.l2.out
${PACKAGE}FILES+=		regress.m1.out
${PACKAGE}FILES+=		regress.m2.out
${PACKAGE}FILES+=		regress.m3.out
${PACKAGE}FILES+=		regress.m4.out
${PACKAGE}FILES+=		regress.m5.out
${PACKAGE}FILES+=		regress.missingpos1.out
${PACKAGE}FILES+=		regress.s.out
${PACKAGE}FILES+=		regress.sh
${PACKAGE}FILES+=		regress.zero.out

.include <bsd.test.mk>
