# SPDX-License-Identifier: GPL-2.0
#
# Makefile for sensor drivers
#

obj-$(CONFIG_VIDEO_ATOMISP_MT9M114)    += atomisp-mt9m114.o
obj-$(CONFIG_VIDEO_ATOMISP_GC2235)     += atomisp-gc2235.o
obj-$(CONFIG_VIDEO_ATOMISP_OV2722)     += atomisp-ov2722.o
obj-$(CONFIG_VIDEO_ATOMISP_GC0310)     += atomisp-gc0310.o

obj-$(CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER) += atomisp-libmsrlisthelper.o
