# VIA/Wondermedia pinctrl support

obj-$(CONFIG_PINCTRL_WMT)	+= pinctrl-wmt.o
obj-$(CONFIG_PINCTRL_VT8500)	+= pinctrl-vt8500.o
obj-$(CONFIG_PINCTRL_WM8505)	+= pinctrl-wm8505.o
obj-$(CONFIG_PINCTRL_WM8650)	+= pinctrl-wm8650.o
obj-$(CONFIG_PINCTRL_WM8750)	+= pinctrl-wm8750.o
obj-$(CONFIG_PINCTRL_WM8850)	+= pinctrl-wm8850.o
