#	$OpenBSD: Makefile,v 1.24 2021/08/06 06:35:13 jsg Exp $

MAN=	amdcf.4 cnmac.4 intro.4 octboot.4 octcf.4 octcib.4 octcit.4 octciu.4 \
	octcrypto.4 octgmx.4 octgpio.4 octiic.4 octmmc.4 octpcie.4 octpip.4 \
	octrng.4 octrtc.4 octsctl.4 octsmi.4 octuctl.4 octxctl.4 \
	ogx.4 ogxnexus.4

MANSUBDIR=octeon

.include <bsd.prog.mk>
