# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_IMX_DSP)		+= imx-dsp.o
obj-$(CONFIG_IMX_SCU)		+= imx-scu.o misc.o imx-scu-irq.o rm.o imx-scu-soc.o
obj-${CONFIG_IMX_SCMI_CPU_DRV}	+= sm-cpu.o
obj-${CONFIG_IMX_SCMI_MISC_DRV}	+= sm-misc.o
obj-${CONFIG_IMX_SCMI_LMM_DRV}	+= sm-lmm.o
