# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Qualcomm Technologies, Inc. EMAC Gigabit Ethernet driver
#

obj-$(CONFIG_QCOM_EMAC) += qcom-emac.o

qcom-emac-objs := emac_main.o emac_hw.o emac_ethtool.o emac_ptp.o \
		  emac_phy.o emac_rgmii.o emac_sgmii.o
