#
# Makefile for the Novatek NT36523 touchscreen driver.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_NT36523_SPI) += nt36523_ts.o
nt36523_ts-y := nt36xxx.o \
	nt36xxx_fw_update.o
