#
# Copyright (C) 2000 - 2007 Jeff Dike (jdike@{addtoit,linux.intel}.com)
# Licensed under the GPL
#

obj-y = registers.o prctl.o signal.o

USER_OBJS := $(obj-y)

include arch/um/scripts/Makefile.rules
