#
# Makefile for digital gyroscope sensor drivers
#

adis16060-y             := adis16060_core.o
obj-$(CONFIG_ADIS16060) += adis16060.o

adis16260-y             := adis16260_core.o
obj-$(CONFIG_ADIS16260) += adis16260.o
