obj-y		+= clk.o cpu.o cs.o gpio.o irq.o prom.o reset.o setup.o \
		   timer.o dev-dsp.o dev-enet.o dev-flash.o dev-pcmcia.o \
		   dev-rng.o dev-spi.o dev-uart.o dev-wdt.o dev-usb-usbd.o
obj-$(CONFIG_EARLY_PRINTK)	+= early_printk.o

obj-y		+= boards/
