#
# Makefile for all Linux ACPI interpreter subdirectories
#

obj-y := utalloc.o utdebug.o uteval.o utinit.o utmisc.o utxface.o \
		utcopy.o utdelete.o utglobal.o utmath.o utobject.o \
		utstate.o utmutex.o utobject.o utcache.o utresrc.o

EXTRA_CFLAGS += $(ACPI_CFLAGS)
