.\" Copyright (c) 1985, 1991 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)ieee.3	6.4 (Berkeley) 5/6/91
.\" $FreeBSD$
.\"
.Dd December 16, 2007
.Dt ILOGB 3
.Os
.Sh NAME
.Nm ilogb ,
.Nm ilogbf ,
.Nm ilogbl ,
.Nm logb ,
.Nm logbf ,
.Nm logbl
.Nd extract exponent
.Sh LIBRARY
.Lb libm
.Sh SYNOPSIS
.In math.h
.Ft int
.Fn ilogb "double x"
.Ft int
.Fn ilogbf "float x"
.Ft int
.Fn ilogbl "long double x"
.Ft double
.Fn logb "double x"
.Ft float
.Fn logbf "float x"
.Ft long double
.Fn logbl "long double x"
.Sh DESCRIPTION
.Fn ilogb ,
.Fn ilogbf
and
.Fn ilogbl
return
.Fa x Ns 's exponent
in integer format.
.Fn ilogb \*(Pm\*(If
returns
.Dv INT_MAX ,
.Fn ilogb \*(Pm\*(Na
returns
.Dv FP_ILOGBNAN ,
and
.Fn ilogb 0
returns
.Dv FP_ILOGB0 .
.Pp
.Fn logb x ,
.Fn logbf x ,
and
.Fn logbl x
return
.Fa x Ns 's exponent
in floating\-point format with the same precision as
.Fa x .
.Fn logb \*(Pm\*(If
returns +\*(If, and
.Fn logb 0
returns -\*(If with a division by zero exception.
.Sh SEE ALSO
.Xr frexp 3 ,
.Xr ieee 3 ,
.Xr math 3 ,
.Xr scalbn 3
.Sh STANDARDS
The
.Fn ilogb ,
.Fn ilogbf ,
.Fn ilogbl ,
.Fn logb ,
.Fn logbf ,
and
.Fn logbl
routines conform to
.St -isoC-99 .
The latter three
implement the logb function recommended by
.St -ieee754 .
.Sh HISTORY
.Bl -tag -width "Function " -compact
.It Em Function
.Em "First Appeared In"
.It Fn logb
.Bx 4.3
.It Fn ilogb
.Fx 1.1.5
.It Fn ilogbf
.Fx 2.0
.It Fn logbf
.Fx 2.0
.It Fn ilogbl
.Fx 5.4
.It Fn logbl
.Fx 8.0
.El
