# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_NOMADIK) += \
	ste-nomadik-s8815.dtb \
	ste-nomadik-nhk15.dtb
dtb-$(CONFIG_ARCH_SPEAR13XX) += \
	spear1310-evb.dtb \
	spear1340-evb.dtb
dtb-$(CONFIG_ARCH_SPEAR3XX) += \
	spear300-evb.dtb \
	spear310-evb.dtb \
	spear320-evb.dtb \
	spear320-hmi.dtb
dtb-$(CONFIG_ARCH_SPEAR6XX) += \
	spear600-evb.dtb
dtb-$(CONFIG_ARCH_STI) += \
	stih410-b2260.dtb \
	stih418-b2199.dtb \
	stih418-b2264.dtb

stm32mp13xx-dhcor-dhsbc-overlay-rb-tft32-v2-dtbs := \
	stm32mp135f-dhcor-dhsbc.dtb \
	stm32mp13xx-dhcor-dhsbc-overlay-rb-tft32-v2.dtbo

stm32mp15xx-avenger96-overlay-644-100-x6-otm8009a-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-644-100-x6-otm8009a.dtbo

stm32mp15xx-avenger96-overlay-644-100-x6-rpi7inch-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-644-100-x6-rpi7inch.dtbo

stm32mp15xx-avenger96-overlay-fdcan1-x6-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-fdcan1-x6.dtbo

stm32mp15xx-avenger96-overlay-fdcan2-x6-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-fdcan2-x6.dtbo

stm32mp15xx-avenger96-overlay-i2c1-eeprom-x6-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-i2c1-eeprom-x6.dtbo

stm32mp15xx-avenger96-overlay-i2c2-eeprom-x6-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-i2c2-eeprom-x6.dtbo

stm32mp15xx-avenger96-overlay-ov5640-x7-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-ov5640-x7.dtbo

stm32mp15xx-avenger96-overlay-spi2-eeprom-x6-dtbs := \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-spi2-eeprom-x6.dtbo

stm32mp15xx-dhcom-drc02-overlay-wifi-rsi-dtbs := \
	stm32mp153c-dhcom-drc02.dtb \
	stm32mp15xx-dhcom-drc02-overlay-wifi-rsi.dtbo

stm32mp15xx-dhcom-pdk2-overlay-460-200-x11-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-460-200-x11.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-497-200-x12-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-497-200-x12.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-531-100-x21-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x21.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-531-100-x22-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x22.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-505-200-x12-ch101olhlwh-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-505-200-x12-ch101olhlwh.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-560-200-x12-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-560-200-x12.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-638-100-x12-rpi7inch-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-638-100-x12-rpi7inch.dtbo \

stm32mp15xx-dhcom-pdk2-overlay-672-100-x18-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-672-100-x18.dtbo \

stm32mp15xx-dhcom-picoitx-overlay-548-200-x2-mi0700s4t-6-dtbs := \
	stm32mp157c-dhcom-picoitx.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-548-200-x2-mi0700s4t-6.dtbo \

stm32mp15xx-dhcom-picoitx-overlay-553-100-x2-tst043015cmhx-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-553-100-x2-tst043015cmhx.dtbo \

stm32mp15xx-dhcom-picoitx-overlay-626-100-x2-ch101olhlwh-dtbs := \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-626-100-x2-ch101olhlwh.dtbo \

dtb-$(CONFIG_ARCH_STM32) += \
	stm32f429-disco.dtb \
	stm32f469-disco.dtb \
	stm32f746-disco.dtb \
	stm32f769-disco.dtb \
	stm32f769-disco-mb1166-reva09.dtb \
	stm32429i-eval.dtb \
	stm32746g-eval.dtb \
	stm32h743i-eval.dtb \
	stm32h743i-disco.dtb \
	stm32h747i-disco.dtb \
	stm32h750i-art-pi.dtb \
	stm32mp133c-prihmb.dtb \
	stm32mp135f-dhcor-dhsbc.dtb \
	stm32mp13xx-dhcor-dhsbc-overlay-rb-tft32-v2.dtb \
	stm32mp13xx-dhcor-dhsbc-overlay-rb-tft32-v2.dtbo \
	stm32mp135f-dk.dtb \
	stm32mp151a-prtt1a.dtb \
	stm32mp151a-prtt1c.dtb \
	stm32mp151a-prtt1s.dtb \
	stm32mp151a-dhcor-testbench.dtb \
	stm32mp151c-mecio1r0.dtb \
	stm32mp151c-mect1s.dtb \
	stm32mp151c-plyaqm.dtb \
	stm32mp153c-dhcom-drc02.dtb \
	stm32mp15xx-dhcom-drc02-overlay-wifi-rsi.dtb \
	stm32mp15xx-dhcom-drc02-overlay-wifi-rsi.dtbo \
	stm32mp153c-dhcor-drc-compact.dtb \
	stm32mp153c-lxa-fairytux2-gen1.dtb \
	stm32mp153c-lxa-fairytux2-gen2.dtb \
	stm32mp153c-lxa-tac-gen3.dtb \
	stm32mp153c-mecio1r1.dtb \
	stm32mp157a-avenger96.dtb \
	stm32mp15xx-avenger96-overlay-644-100-x6-otm8009a.dtb \
	stm32mp15xx-avenger96-overlay-644-100-x6-otm8009a.dtbo \
	stm32mp15xx-avenger96-overlay-644-100-x6-rpi7inch.dtb \
	stm32mp15xx-avenger96-overlay-644-100-x6-rpi7inch.dtbo \
	stm32mp15xx-avenger96-overlay-fdcan1-x6.dtb \
	stm32mp15xx-avenger96-overlay-fdcan1-x6.dtbo \
	stm32mp15xx-avenger96-overlay-fdcan2-x6.dtb \
	stm32mp15xx-avenger96-overlay-fdcan2-x6.dtbo \
	stm32mp15xx-avenger96-overlay-i2c1-eeprom-x6.dtb \
	stm32mp15xx-avenger96-overlay-i2c1-eeprom-x6.dtbo \
	stm32mp15xx-avenger96-overlay-i2c2-eeprom-x6.dtb \
	stm32mp15xx-avenger96-overlay-i2c2-eeprom-x6.dtbo \
	stm32mp15xx-avenger96-overlay-ov5640-x7.dtb \
	stm32mp15xx-avenger96-overlay-ov5640-x7.dtbo \
	stm32mp15xx-avenger96-overlay-spi2-eeprom-x6.dtb \
	stm32mp15xx-avenger96-overlay-spi2-eeprom-x6.dtbo \
	stm32mp157a-dhcor-avenger96.dtb \
	stm32mp157a-dk1.dtb \
	stm32mp157a-dk1-scmi.dtb \
	stm32mp157a-iot-box.dtb \
	stm32mp157a-microgea-stm32mp1-microdev2.0.dtb \
	stm32mp157a-microgea-stm32mp1-microdev2.0-of7.dtb \
	stm32mp157a-icore-stm32mp1-ctouch2.dtb \
	stm32mp157a-icore-stm32mp1-ctouch2-of10.dtb \
	stm32mp157a-icore-stm32mp1-edimm2.2.dtb \
	stm32mp157a-stinger96.dtb \
	stm32mp157c-dhcom-pdk2.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-460-200-x11.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-460-200-x11.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-497-200-x12.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-497-200-x12.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x21.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x21.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x22.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-531-100-x22.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-505-200-x12-ch101olhlwh.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-505-200-x12-ch101olhlwh.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-560-200-x12.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-560-200-x12.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-638-100-x12-rpi7inch.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-638-100-x12-rpi7inch.dtbo \
	stm32mp15xx-dhcom-pdk2-overlay-672-100-x18.dtb \
	stm32mp15xx-dhcom-pdk2-overlay-672-100-x18.dtbo \
	stm32mp157c-dhcom-picoitx.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-548-200-x2-mi0700s4t-6.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-548-200-x2-mi0700s4t-6.dtbo \
	stm32mp15xx-dhcom-picoitx-overlay-553-100-x2-tst043015cmhx.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-553-100-x2-tst043015cmhx.dtbo \
	stm32mp15xx-dhcom-picoitx-overlay-626-100-x2-ch101olhlwh.dtb \
	stm32mp15xx-dhcom-picoitx-overlay-626-100-x2-ch101olhlwh.dtbo \
	stm32mp157c-dk2.dtb \
	stm32mp157c-dk2-scmi.dtb \
	stm32mp157c-ed1.dtb \
	stm32mp157c-ed1-scmi.dtb \
	stm32mp157c-emsbc-argon.dtb \
	stm32mp157c-ev1.dtb \
	stm32mp157c-ev1-scmi.dtb \
	stm32mp157c-lxa-mc1.dtb \
	stm32mp157c-lxa-tac-gen1.dtb \
	stm32mp157c-lxa-tac-gen2.dtb \
	stm32mp157c-odyssey.dtb \
	stm32mp157c-osd32mp1-red.dtb \
	stm32mp157c-phyboard-sargas-rdk.dtb \
	stm32mp157c-ultra-fly-sbc.dtb \
	stm32mp157f-dk2.dtb
dtb-$(CONFIG_ARCH_U8500) += \
	ste-snowball.dtb \
	ste-hrefprev60-stuib.dtb \
	ste-hrefprev60-tvk.dtb \
	ste-hrefv60plus-stuib.dtb \
	ste-hrefv60plus-tvk.dtb \
	ste-href520-tvk.dtb \
	ste-ux500-samsung-golden.dtb \
	ste-ux500-samsung-janice.dtb \
	ste-ux500-samsung-gavini.dtb \
	ste-ux500-samsung-codina.dtb \
	ste-ux500-samsung-codina-tmo.dtb \
	ste-ux500-samsung-skomer.dtb \
	ste-ux500-samsung-kyle.dtb
