# SPDX-License-Identifier: GPL-2.0
# Makefile for net selftests

TEST_PROGS := dev_addr_lists.sh propagation.sh options.sh

TEST_INCLUDES := \
	../bonding/lag_lib.sh \
	../../../net/forwarding/lib.sh \
	../../../net/lib.sh \
	../../../net/in_netns.sh \
	../../../net/lib/sh/defer.sh

include ../../../lib.mk
