# $FreeBSD$

PACKAGE=lib${LIB}

INCS=	capsicum_helpers.h

MAN+=	capsicum_helpers.3

MLINKS+=capsicum_helpers.3 caph_enter.3
MLINKS+=capsicum_helpers.3 caph_enter_casper.3
MLINKS+=capsicum_helpers.3 caph_rights_limit.3
MLINKS+=capsicum_helpers.3 caph_fcntls_limit.3
MLINKS+=capsicum_helpers.3 caph_ioctls_limit.3
MLINKS+=capsicum_helpers.3 caph_limit_stream.3
MLINKS+=capsicum_helpers.3 caph_limit_stdin.3
MLINKS+=capsicum_helpers.3 caph_limit_stderr.3
MLINKS+=capsicum_helpers.3 caph_limit_stdout.3
MLINKS+=capsicum_helpers.3 caph_limit_stdio.3
MLINKS+=capsicum_helpers.3 caph_cache_tzdata.3
MLINKS+=capsicum_helpers.3 caph_cache_catpages.3

.include <bsd.lib.mk>
