.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek.
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)index.3	8.1 (Berkeley) 6/4/93
.\" $FreeBSD$
.\"
.Dd March 20, 2011
.Dt INDEX 3
.Os
.Sh NAME
.Nm index , rindex
.Nd locate character in string
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In strings.h
.Ft "char *"
.Fn index "const char *s" "int c"
.Ft "char *"
.Fn rindex "const char *s" "int c"
.Sh DESCRIPTION
.Bf -symbolic
The
.Fn index
and
.Fn rindex
functions have been deprecated in favor of
.Xr strchr 3
and
.Xr strrchr 3 .
.Ef
.Pp
The
.Fn index
function
locates the first occurrence of
.Fa c
(converted to a
.Vt char )
in the string pointed to by
.Fa s .
The terminating null character is considered part of the string;
therefore if
.Fa c
is
.Ql \e0 ,
the functions locate the terminating
.Ql \e0 .
.Pp
The
.Fn rindex
function is identical to
.Fn index ,
except it locates the last occurrence of
.Fa c .
.Sh RETURN VALUES
The functions
.Fn index
and
.Fn rindex
return a pointer to the located character, or
.Dv NULL
if the character does not appear in the string.
.Sh SEE ALSO
.Xr memchr 3 ,
.Xr strchr 3 ,
.Xr strcspn 3 ,
.Xr strpbrk 3 ,
.Xr strrchr 3 ,
.Xr strsep 3 ,
.Xr strspn 3 ,
.Xr strstr 3 ,
.Xr strtok 3
.Sh HISTORY
The
.Fn index
and
.Fn rindex
functions appeared in
.At v6 .
Their prototypes existed previously in
.In string.h
before they were moved to
.In strings.h
for
.St -p1003.1-2001
compliance.
The functions are not specified by
.St -p1003.1-2008 .
