obj-$(CONFIG_CRYPTO_DEV_NX) += nx-crypto.o
nx-crypto-objs := nx.o \
		  nx_debugfs.o \
		  nx-aes-cbc.o \
		  nx-aes-ecb.o \
		  nx-aes-gcm.o \
		  nx-aes-ccm.o \
		  nx-aes-ctr.o \
		  nx-aes-xcbc.o \
		  nx-sha256.o \
		  nx-sha512.o
