#
# arch/blackfin/mach-bf533/boards/Makefile
#

obj-$(CONFIG_GENERIC_BOARD)            += generic_board.o
obj-$(CONFIG_BFIN533_STAMP)            += stamp.o
obj-$(CONFIG_BFIN533_EZKIT)            += ezkit.o
obj-$(CONFIG_BFIN533_BLUETECHNIX_CM)   += cm_bf533.o
