#
# arch/blackfin/mach-bf533/boards/Makefile
#

obj-$(CONFIG_BFIN533_STAMP)            += stamp.o
obj-$(CONFIG_BFIN532_IP0X)             += ip0x.o
obj-$(CONFIG_BFIN533_EZKIT)            += ezkit.o
obj-$(CONFIG_BFIN533_BLUETECHNIX_CM)   += cm_bf533.o
obj-$(CONFIG_BLACKSTAMP)               += blackstamp.o
obj-$(CONFIG_H8606_HVSISTEMAS)         += H8606.o
