#
# Makefile for the 'controller' sub-component of DAL.
# It provides the control and status of HW CRTC block.


DCE120 = dce120_resource.o dce120_timing_generator.o \
dce120_hw_sequencer.o

AMD_DAL_DCE120 = $(addprefix $(AMDDALPATH)/dc/dce120/,$(DCE120))

AMD_DISPLAY_FILES += $(AMD_DAL_DCE120)