/*
 * arch/arm/mach-spear3xx/include/mach/debug-macro.S
 *
 * Debugging macro include header spear3xx machine family
 *
 * Copyright (C) 2009 ST Microelectronics
 * Viresh Kumar<viresh.linux@gmail.com>
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2. This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#include <plat/debug-macro.S>
