# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Rockchip RK628 display bridge driver.
#

obj-$(CONFIG_DRM_ROCKCHIP_RK628) += rk628_combtxphy.o \
				    rk628_dsi.o \
				    rk628_gvi.o \
				    rk628_lvds.o \
				    rk628_post_process.o \
				    rk628_rgb.o \
				    rk628_hdmi.o
