# SPDX-License-Identifier: GPL-2.0
# Generic MAILBOX API

obj-$(CONFIG_MAILBOX)		+= mailbox.o

obj-$(CONFIG_MAILBOX_TEST)	+= mailbox-test.o

obj-$(CONFIG_ARM_MHU)	+= arm_mhu.o arm_mhu_db.o

obj-$(CONFIG_ARM_MHU_V2)	+= arm_mhuv2.o

obj-$(CONFIG_ARM_MHU_V3)	+= arm_mhuv3.o

obj-$(CONFIG_AST2700_MBOX)	+= ast2700-mailbox.o

obj-$(CONFIG_CV1800_MBOX)	+= cv1800-mailbox.o

obj-$(CONFIG_EXYNOS_MBOX)	+= exynos-mailbox.o

obj-$(CONFIG_IMX_MBOX)	+= imx-mailbox.o

obj-$(CONFIG_ARMADA_37XX_RWTM_MBOX)	+= armada-37xx-rwtm-mailbox.o

obj-$(CONFIG_PLATFORM_MHU)	+= platform_mhu.o

obj-$(CONFIG_PL320_MBOX)	+= pl320-ipc.o

obj-$(CONFIG_OMAP2PLUS_MBOX)	+= omap-mailbox.o

obj-$(CONFIG_ROCKCHIP_MBOX)	+= rockchip-mailbox.o

obj-$(CONFIG_PCC)		+= pcc.o

obj-$(CONFIG_ALTERA_MBOX)	+= mailbox-altera.o

obj-$(CONFIG_BCM2835_MBOX)	+= bcm2835-mailbox.o

obj-$(CONFIG_STI_MBOX)		+= mailbox-sti.o

obj-$(CONFIG_TI_MESSAGE_MANAGER) += ti-msgmgr.o

obj-$(CONFIG_XGENE_SLIMPRO_MBOX) += mailbox-xgene-slimpro.o

obj-$(CONFIG_HI3660_MBOX)	+= hi3660-mailbox.o

obj-$(CONFIG_HI6220_MBOX)	+= hi6220-mailbox.o

obj-$(CONFIG_BCM_PDC_MBOX)	+= bcm-pdc-mailbox.o

obj-$(CONFIG_BCM_FLEXRM_MBOX)	+= bcm-flexrm-mailbox.o

obj-$(CONFIG_POLARFIRE_SOC_MAILBOX)	+= mailbox-mpfs.o

obj-$(CONFIG_MCHP_SBI_IPC_MBOX)		+= mailbox-mchp-ipc-sbi.o

obj-$(CONFIG_QCOM_APCS_IPC)	+= qcom-apcs-ipc-mailbox.o

obj-$(CONFIG_TEGRA_HSP_MBOX)	+= tegra-hsp.o

obj-$(CONFIG_STM32_IPCC) 	+= stm32-ipcc.o

obj-$(CONFIG_MTK_ADSP_MBOX)	+= mtk-adsp-mailbox.o

obj-$(CONFIG_MTK_CMDQ_MBOX)	+= mtk-cmdq-mailbox.o

obj-$(CONFIG_MTK_GPUEB_MBOX)	+= mtk-gpueb-mailbox.o

obj-$(CONFIG_ZYNQMP_IPI_MBOX)	+= zynqmp-ipi-mailbox.o

obj-$(CONFIG_SUN6I_MSGBOX)	+= sun6i-msgbox.o

obj-$(CONFIG_SPRD_MBOX)		+= sprd-mailbox.o

obj-$(CONFIG_QCOM_CPUCP_MBOX)	+= qcom-cpucp-mbox.o

obj-$(CONFIG_QCOM_IPCC)		+= qcom-ipcc.o

obj-$(CONFIG_THEAD_TH1520_MBOX)	+= mailbox-th1520.o

obj-$(CONFIG_CIX_MBOX)	+= cix-mailbox.o

obj-$(CONFIG_BCM74110_MAILBOX)	+= bcm74110-mailbox.o

obj-$(CONFIG_RISCV_SBI_MPXY_MBOX)	+= riscv-sbi-mpxy-mbox.o
