# SPDX-License-Identifier: GPL-2.0-only
snd-soc-sdw-utils-y := soc_sdw_utils.o soc_sdw_dmic.o soc_sdw_rt_dmic.o \
		       soc_sdw_rt700.o soc_sdw_rt711.o 			\
		       soc_sdw_rt5682.o soc_sdw_rt_sdca_jack_common.o	\
		       soc_sdw_rt_amp.o soc_sdw_rt_mf_sdca.o		\
		       soc_sdw_bridge_cs35l56.o 			\
		       soc_sdw_cs42l42.o soc_sdw_cs42l43.o 		\
		       soc_sdw_cs_amp.o					\
		       soc_sdw_maxim.o
obj-$(CONFIG_SND_SOC_SDW_UTILS) += snd-soc-sdw-utils.o
