#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@suse.cz>
#

snd-vx-cs-objs := vx_entry.o vxp_ops.o vxp_mixer.o
snd-vxpocket-objs := vxpocket.o
snd-vxp440-objs := vxp440.o

obj-$(CONFIG_SND_VXPOCKET) += snd-vxpocket.o snd-vx-cs.o
obj-$(CONFIG_SND_VXP440) += snd-vxp440.o snd-vx-cs.o
