obj-$(CONFIG_VIDEO_ROCKCHIP_VDEC) += rockchip-vdec.o

rockchip-vdec-y += \
		   rkvdec.o \
		   rkvdec-cabac.o \
		   rkvdec-h264.o \
		   rkvdec-h264-common.o \
		   rkvdec-hevc.o \
		   rkvdec-hevc-common.o \
		   rkvdec-rcb.o \
		   rkvdec-vp9.o
