/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Automatically generated by rvgen kunit.
 * May need manual intervention for function prototypes that couldn't be
 * found (e.g. are in another file) or variables to be exported.
 */

#ifndef __PAGEFAULT_KUNIT_H
#define __PAGEFAULT_KUNIT_H

#if IS_ENABLED(CONFIG_RV_MONITORS_KUNIT_TEST)

#include <linux/rv.h>
#include <rv/kunit.h>

extern const struct rv_pagefault_ops {
	struct rv_kunit_mon mon;
	void (*handle_page_fault)(void *data, unsigned long address, struct pt_regs *regs,
			      unsigned long error_code);
	void (*handle_task_newtask)(void *data, struct task_struct *task, u64 flags);
} rv_pagefault_ops;
#endif

#endif /* __PAGEFAULT_KUNIT_H */
