.\" Copyright (c) 2005 Michael Bushkov <bushman@rsu.ru>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd October 5, 2018
.Dt NSCD 8
.Os
.Sh NAME
.Nm nscd
.Nd "name service caching daemon"
.Sh SYNOPSIS
.Nm
.Op Fl dnst
.Op Fl i Ar cachename
.Op Fl I Ar cachename
.Sh DESCRIPTION
The
.Nm
utility
is the system caching daemon.
It can cache almost all types of data and is basically intended to be used
with the
.Nm nsswitch
subsystem.
The cache is actually per-user.
This means that each user can work only with the
cached data that were cached by themselves, and cannot poison the
cache of other users.
The
.Nm
utility supports two types of caching:
.Bl -tag -width ".Sy Type"
.It Sy Type
.Sy Description
.It Common caching
Each cached element is the key+value pair.
This type of caching supports policies which are applied when maximum
number of cached elements is exceeded.
Three policies are available:
.Cm FIFO
(first in - first out),
.Cm LRU
(least recently used) and
.Cm LFU
(least frequently used).
This type of caching is used with the
.Fn getXXXbyname
family of functions.
.It Multipart caching
Each cached element is the part of the elements sequence.
This type of caching is intended to be used with the
.Fn getXXXent
family of functions.
.El
.Pp
The
.Nm
utility is able not only to cache elements, but to perform the actual nsswitch
lookups by itself.
To enable this feature, use the
.Va perform-actual-lookups
parameter in
.Xr nscd.conf 5 .
.Pp
The
.Nm
utility recognizes the following runtime options:
.Bl -tag -width indent
.\" .It Fl d
.\" XXX Document me!
.It Fl n
Do not daemonize;
.Nm
will not fork or disconnect itself from the terminal.
.It Fl s
Single-threaded mode.
Forces using only one thread for all processing purposes (it overrides
the
.Va threads
parameter in the
.Xr nscd.conf 5
file).
.It Fl t
Trace mode.
All trace messages will be written to stdout.
This mode is usually used with
.Fl n
and
.Fl s
flags are used for debugging purposes.
.It Fl i Ar cachename
Invalidates personal cache.
When specified,
.Nm
acts as the administration tool.
It asks the already running
.Nm
to invalidate the specified part of the cache of the
calling user.
For example, sometimes you may want to invalidate your
.Dq Li hosts
cache.
You can specify
.Dq Li all
as the
.Ar cachename
to invalidate your personal cache as a whole.
You cannot use this option for the
.Ar cachename
for which the
.Va perform-actual-lookups
option is enabled.
.It Fl I Ar cachename
Invalidates the cache for every user.
When specified,
.Nm
acts as the administration tool.
It asks the already
running
.Nm
to invalidate the specified part of the cache for
every user.
You can specify
.Dq Li all
as the
.Ar cachename
to invalidate the whole cache.
Only the root can use this option.
.El
.Sh FILES
.Bl -tag -width ".Pa /etc/nscd.conf" -compact
.It Pa /etc/nscd.conf
The default configuration file.
.El
.Sh SEE ALSO
.Xr nsdispatch 3 ,
.Xr nscd.conf 5 ,
.Xr nsswitch.conf 5
.Sh AUTHORS
.An Michael Bushkov Aq Mt bushman@FreeBSD.org
