#!/bin/sh
set -e

case "$0::$1" in
*.postinst::configure|*.postrm::remove)
	depmod -a -F /boot/System.map-=V =V || true
	for dir in "/etc/kernel/postinst.d" "/etc/kernel/postinst.d/=V"
	do
		if [ -d "$dir" ]; then
			run-parts --verbose --exit-on-error --arg="=V" --arg="/boot/=K-=V" "$dir"
		fi
	done
	;;
esac
