#
# Makefile for display transmitter like lvds edp mipi
#
obj-$(CONFIG_RK2928_LVDS)          += rk2928_lvds.o
obj-$(CONFIG_RK610_LVDS)	  += rk610_lcd.o
obj-$(CONFIG_RK616_LVDS)          += rk616_lvds.o
obj-$(CONFIG_TC358768_RGB2MIPI)   += mipi_dsi.o tc358768.o
obj-$(CONFIG_SSD2828_RGB2MIPI)   += mipi_dsi.o ssd2828.o
obj-$(CONFIG_DP_ANX6345)          += dp_anx6345.o
obj-$(CONFIG_DP501)          += dp501.o
