# SPDX-License-Identifier: MIT
nvkm-y += nvkm/subdev/privring/gf100.o
nvkm-y += nvkm/subdev/privring/gf117.o
nvkm-y += nvkm/subdev/privring/gk104.o
nvkm-y += nvkm/subdev/privring/gk20a.o
nvkm-y += nvkm/subdev/privring/gm200.o
nvkm-y += nvkm/subdev/privring/gp10b.o
