# SPDX-License-Identifier: GPL-2.0-only
st_lsm6dsr-y := st_lsm6dsr_core.o st_lsm6dsr_buffer.o \
		st_lsm6dsr_shub.o st_lsm6dsr_embfunc.o

obj-$(CONFIG_IIO_ST_LSM6DSR) += st_lsm6dsr.o
obj-$(CONFIG_IIO_ST_LSM6DSR_I2C) += st_lsm6dsr_i2c.o
obj-$(CONFIG_IIO_ST_LSM6DSR_SPI) += st_lsm6dsr_spi.o
