# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2009 - 2018 Intel Corporation.
#
# Makefile for the Intel(R) 82576 VF ethernet driver
#

obj-$(CONFIG_IGBVF) += igbvf.o

igbvf-objs := vf.o \
              mbx.o \
              ethtool.o \
              netdev.o

