@node ntp-keygen Invocation
@section Invoking ntp-keygen
@pindex ntp-keygen
@cindex Create a NTP host key
@ignore
#
# EDIT THIS FILE WITH CAUTION  (invoke-ntp-keygen.texi)
#
# It has been AutoGen-ed  February 20, 2019 at 09:57:13 AM by AutoGen 5.18.5
# From the definitions    ntp-keygen-opts.def
# and the template file   agtexi-cmd.tpl
@end ignore



This program generates cryptographic data files used by the NTPv4
authentication and identification schemes.
It can generate message digest keys used in symmetric key cryptography and,
if the OpenSSL software library has been installed, it can generate host keys,
signing keys, certificates, and identity keys and parameters used in Autokey
public key cryptography.
These files are used for cookie encryption,
digital signature, and challenge/response identification algorithms
compatible with the Internet standard security infrastructure.

The message digest symmetric keys file is generated in a format
compatible with NTPv3.
All other files are in PEM-encoded printable ASCII format,
so they can be embedded as MIME attachments in email to other sites
and certificate authorities.
By default, files are not encrypted.

When used to generate message digest symmetric keys, the program
produces a file containing ten pseudo-random printable ASCII strings
suitable for the MD5 message digest algorithm included in the
distribution.
If the OpenSSL library is installed, it produces an additional ten
hex-encoded random bit strings suitable for SHA1, AES-128-CMAC, and
other message digest algorithms.
The message digest symmetric keys file must be distributed and stored
using secure means beyond the scope of NTP itself.
Besides the keys used for ordinary NTP associations, additional keys
can be defined as passwords for the
@code{ntpq(1ntpqmdoc)}
and
@code{ntpdc(1ntpdcmdoc)}
utility programs.

The remaining generated files are compatible with other OpenSSL
applications and other Public Key Infrastructure (PKI) resources.
Certificates generated by this program are compatible with extant
industry practice, although some users might find the interpretation of
X509v3 extension fields somewhat liberal.
However, the identity keys are probably not compatible with anything
other than Autokey.

Some files used by this program are encrypted using a private password.
The
@code{-p}
option specifies the read password for local encrypted files and the
@code{-q}
option the write password for encrypted files sent to remote sites.
If no password is specified, the host name returned by the Unix
@code{hostname(1)}
command, normally the DNS name of the host, is used as the the default read
password, for convenience.
The
@code{ntp-keygen}
program prompts for the password if it reads an encrypted file
and the password is missing or incorrect.
If an encrypted file is read successfully and
no write password is specified, the read password is used
as the write password by default.

The
@code{pw}
option of the
@code{crypto}
@code{ntpd(1ntpdmdoc)}
configuration command specifies the read
password for previously encrypted local files.
This must match the local read password used by this program.
If not specified, the host name is used.
Thus, if files are generated by this program without an explicit password,
they can be read back by
@code{ntpd(1ntpdmdoc)}
without specifying an explicit password but only on the same host.
If the write password used for encryption is specified as the host name,
these files can be read by that host with no explicit password.

Normally, encrypted files for each host are generated by that host and
used only by that host, although exceptions exist as noted later on
this page.
The symmetric keys file, normally called
@file{ntp.keys},
is usually installed in
@file{/etc}.
Other files and links are usually installed in
@file{/usr/local/etc},
which is normally in a shared filesystem in
NFS-mounted networks and cannot be changed by shared clients.
In these cases, NFS clients can specify the files in another
directory such as
@file{/etc}
using the
@code{keysdir}
@code{ntpd(1ntpdmdoc)}
configuration file command.

This program directs commentary and error messages to the standard
error stream
@file{stderr}
and remote files to the standard output stream
@file{stdout}
where they can be piped to other applications or redirected to files.
The names used for generated files and links all begin with the
string
@file{ntpkey*}
and include the file type, generating host and filestamp,
as described in the
@ref{Cryptographic Data Files}
section below.

@subsubsection Running the Program
The safest way to run the
@code{ntp-keygen}
program is logged in directly as root.
The recommended procedure is change to the
@kbd{keys}
directory, usually
@file{/usr/local/etc},
then run the program.

To test and gain experience with Autokey concepts, log in as root and
change to the
@kbd{keys}
directory, usually
@file{/usr/local/etc}.
When run for the first time, or if all files with names beginning with
@file{ntpkey*}
have been removed, use the
@code{ntp-keygen}
command without arguments to generate a default
@code{RSA}
host key and matching
@code{RSA-MD5}
certificate file with expiration date one year hence,
which is all that is necessary in many cases.
The program also generates soft links from the generic names
to the respective files.
If run again without options, the program uses the
existing keys and parameters and generates a new certificate file with
new expiration date one year hence, and soft link.

The host key is used to encrypt the cookie when required and so must be
@code{RSA}
type.
By default, the host key is also the sign key used to encrypt signatures.
When necessary, a different sign key can be specified and this can be
either
@code{RSA}
or
@code{DSA}
type.
By default, the message digest type is
@code{MD5},
but any combination
of sign key type and message digest type supported by the OpenSSL library
can be specified, including those using the
@code{AES128CMAC}, @code{MD2}, @code{MD5}, @code{MDC2}, @code{SHA}, @code{SHA1}
and
@code{RIPE160}
message digest algorithms.
However, the scheme specified in the certificate must be compatible
with the sign key.
Certificates using any digest algorithm are compatible with
@code{RSA}
sign keys;
however, only
@code{SHA}
and
@code{SHA1}
certificates are compatible with
@code{DSA}
sign keys.

Private/public key files and certificates are compatible with
other OpenSSL applications and very likely other libraries as well.
Certificates or certificate requests derived from them should be compatible
with extant industry practice, although some users might find
the interpretation of X509v3 extension fields somewhat liberal.
However, the identification parameter files, although encoded
as the other files, are probably not compatible with anything other than Autokey.

Running the program as other than root and using the Unix
@code{su(1)}
command
to assume root may not work properly, since by default the OpenSSL library
looks for the random seed file
@file{.rnd}
in the user home directory.
However, there should be only one
@file{.rnd},
most conveniently
in the root directory, so it is convenient to define the
.Ev RANDFILE
environment variable used by the OpenSSL library as the path to
@file{.rnd}.

Installing the keys as root might not work in NFS-mounted
shared file systems, as NFS clients may not be able to write
to the shared keys directory, even as root.
In this case, NFS clients can specify the files in another
directory such as
@file{/etc}
using the
@code{keysdir}
@code{ntpd(1ntpdmdoc)}
configuration file command.
There is no need for one client to read the keys and certificates
of other clients or servers, as these data are obtained automatically
by the Autokey protocol.

Ordinarily, cryptographic files are generated by the host that uses them,
but it is possible for a trusted agent (TA) to generate these files
for other hosts; however, in such cases files should always be encrypted.
The subject name and trusted name default to the hostname
of the host generating the files, but can be changed by command line options.
It is convenient to designate the owner name and trusted name
as the subject and issuer fields, respectively, of the certificate.
The owner name is also used for the host and sign key files,
while the trusted name is used for the identity files.

All files are installed by default in the keys directory
@file{/usr/local/etc},
which is normally in a shared filesystem
in NFS-mounted networks.
The actual location of the keys directory
and each file can be overridden by configuration commands,
but this is not recommended.
Normally, the files for each host are generated by that host
and used only by that host, although exceptions exist
as noted later on this page.

Normally, files containing private values,
including the host key, sign key and identification parameters,
are permitted root read/write-only;
while others containing public values are permitted world readable.
Alternatively, files containing private values can be encrypted
and these files permitted world readable,
which simplifies maintenance in shared file systems.
Since uniqueness is insured by the
@kbd{hostname}
and
@kbd{filestamp}
file name extensions, the files for an NTP server and
dependent clients can all be installed in the same shared directory.

The recommended practice is to keep the file name extensions
when installing a file and to install a soft link
from the generic names specified elsewhere on this page
to the generated files.
This allows new file generations to be activated simply
by changing the link.
If a link is present,
@code{ntpd(1ntpdmdoc)}
follows it to the file name to extract the
@kbd{filestamp}.
If a link is not present,
@code{ntpd(1ntpdmdoc)}
extracts the
@kbd{filestamp}
from the file itself.
This allows clients to verify that the file and generation times
are always current.
The
@code{ntp-keygen}
program uses the same
@kbd{filestamp}
extension for all files generated
at one time, so each generation is distinct and can be readily
recognized in monitoring data.

Run the command on as many hosts as necessary.
Designate one of them as the trusted host (TH) using
@code{ntp-keygen}
with the
@code{-T}
option and configure it to synchronize from reliable Internet servers.
Then configure the other hosts to synchronize to the TH directly or
indirectly.
A certificate trail is created when Autokey asks the immediately
ascendant host towards the TH to sign its certificate, which is then
provided to the immediately descendant host on request.
All group hosts should have acyclic certificate trails ending on the TH.

The host key is used to encrypt the cookie when required and so must be
RSA type.
By default, the host key is also the sign key used to encrypt
signatures.
A different sign key can be assigned using the
@code{-S}
option and this can be either
@code{RSA}
or
@code{DSA}
type.
By default, the signature
message digest type is
@code{MD5},
but any combination of sign key type and
message digest type supported by the OpenSSL library can be specified
using the
@code{-c}
option.

The rules say cryptographic media should be generated with proventic
filestamps, which means the host should already be synchronized before
this program is run.
This of course creates a chicken-and-egg problem
when the host is started for the first time.
Accordingly, the host time
should be set by some other means, such as eyeball-and-wristwatch, at
least so that the certificate lifetime is within the current year.
After that and when the host is synchronized to a proventic source, the
certificate should be re-generated.

Additional information on trusted groups and identity schemes is on the
@quotedblleft{}Autokey Public-Key Authentication@quotedblright{}
page.

File names begin with the prefix
@file{ntpkey}_
and end with the suffix
@file{_}@kbd{hostname}. @kbd{filestamp},
where
@kbd{hostname}
is the owner name, usually the string returned
by the Unix
@code{hostname(1)}
command, and
@kbd{filestamp}
is the NTP seconds when the file was generated, in decimal digits.
This both guarantees uniqueness and simplifies maintenance
procedures, since all files can be quickly removed
by a
@code{rm} @file{ntpkey*}
command or all files generated
at a specific time can be removed by a
@code{rm} @file{*}@kbd{filestamp}
command.
To further reduce the risk of misconfiguration,
the first two lines of a file contain the file name
and generation date and time as comments.

@subsubsection Trusted Hosts and Groups
Each cryptographic configuration involves selection of a signature scheme
and identification scheme, called a cryptotype,
as explained in the
@ref{Authentication Options}
section of
@code{ntp.conf(5)}.
The default cryptotype uses
@code{RSA}
encryption,
@code{MD5}
message digest
and
@code{TC}
identification.
First, configure a NTP subnet including one or more low-stratum
trusted hosts from which all other hosts derive synchronization
directly or indirectly.
Trusted hosts have trusted certificates;
all other hosts have nontrusted certificates.
These hosts will automatically and dynamically build authoritative
certificate trails to one or more trusted hosts.
A trusted group is the set of all hosts that have, directly or indirectly,
a certificate trail ending at a trusted host.
The trail is defined by static configuration file entries
or dynamic means described on the
@ref{Automatic NTP Configuration Options}
section of
@code{ntp.conf(5)}.

On each trusted host as root, change to the keys directory.
To insure a fresh fileset, remove all
@file{ntpkey}
files.
Then run
@code{ntp-keygen}
@code{-T}
to generate keys and a trusted certificate.
On all other hosts do the same, but leave off the
@code{-T}
flag to generate keys and nontrusted certificates.
When complete, start the NTP daemons beginning at the lowest stratum
and working up the tree.
It may take some time for Autokey to instantiate the certificate trails
throughout the subnet, but setting up the environment is completely automatic.

If it is necessary to use a different sign key or different digest/signature
scheme than the default, run
@code{ntp-keygen}
with the
@code{-S} @kbd{type}
option, where
@kbd{type}
is either
@code{RSA}
or
@code{DSA}.
The most frequent need to do this is when a
@code{DSA}-signed
certificate is used.
If it is necessary to use a different certificate scheme than the default,
run
@code{ntp-keygen}
with the
@code{-c} @kbd{scheme}
option and selected
@kbd{scheme}
as needed.
If
@code{ntp-keygen}
is run again without these options, it generates a new certificate
using the same scheme and sign key, and soft link.

After setting up the environment it is advisable to update certificates
from time to time, if only to extend the validity interval.
Simply run
@code{ntp-keygen}
with the same flags as before to generate new certificates
using existing keys, and soft links.
However, if the host or sign key is changed,
@code{ntpd(1ntpdmdoc)}
should be restarted.
When
@code{ntpd(1ntpdmdoc)}
is restarted, it loads any new files and restarts the protocol.
Other dependent hosts will continue as usual until signatures are refreshed,
at which time the protocol is restarted.

@subsubsection Identity Schemes
As mentioned on the Autonomous Authentication page,
the default
@code{TC}
identity scheme is vulnerable to a middleman attack.
However, there are more secure identity schemes available,
including
@code{PC}, @code{IFF}, @code{GQ}
and
@code{MV}
schemes described below.
These schemes are based on a TA, one or more trusted hosts
and some number of nontrusted hosts.
Trusted hosts prove identity using values provided by the TA,
while the remaining hosts prove identity using values provided
by a trusted host and certificate trails that end on that host.
The name of a trusted host is also the name of its sugroup
and also the subject and issuer name on its trusted certificate.
The TA is not necessarily a trusted host in this sense, but often is.

In some schemes there are separate keys for servers and clients.
A server can also be a client of another server,
but a client can never be a server for another client.
In general, trusted hosts and nontrusted hosts that operate
as both server and client have parameter files that contain
both server and client keys.
Hosts that operate
only as clients have key files that contain only client keys.

The PC scheme supports only one trusted host in the group.
On trusted host alice run
@code{ntp-keygen}
@code{-P}
@code{-p} @kbd{password}
to generate the host key file
@file{ntpkey}_ @code{RSA} @file{key_alice.} @kbd{filestamp}
and trusted private certificate file
@file{ntpkey}_ @code{RSA-MD5} @code{_} @file{cert_alice.} @kbd{filestamp},
and soft links.
Copy both files to all group hosts;
they replace the files which would be generated in other schemes.
On each host
@kbd{bob}
install a soft link from the generic name
@file{ntpkey_host_}@kbd{bob}
to the host key file and soft link
@file{ntpkey_cert_}@kbd{bob}
to the private certificate file.
Note the generic links are on bob, but point to files generated
by trusted host alice.
In this scheme it is not possible to refresh
either the keys or certificates without copying them
to all other hosts in the group, and recreating the soft links.

For the
@code{IFF}
scheme proceed as in the
@code{TC}
scheme to generate keys
and certificates for all group hosts, then for every trusted host in the group,
generate the
@code{IFF}
parameter file.
On trusted host alice run
@code{ntp-keygen}
@code{-T}
@code{-I}
@code{-p} @kbd{password}
to produce her parameter file
@file{ntpkey_IFFpar_alice.}@kbd{filestamp},
which includes both server and client keys.
Copy this file to all group hosts that operate as both servers
and clients and install a soft link from the generic
@file{ntpkey_iff_alice}
to this file.
If there are no hosts restricted to operate only as clients,
there is nothing further to do.
As the
@code{IFF}
scheme is independent
of keys and certificates, these files can be refreshed as needed.

If a rogue client has the parameter file, it could masquerade
as a legitimate server and present a middleman threat.
To eliminate this threat, the client keys can be extracted
from the parameter file and distributed to all restricted clients.
After generating the parameter file, on alice run
@code{ntp-keygen}
@code{-e}
and pipe the output to a file or email program.
Copy or email this file to all restricted clients.
On these clients install a soft link from the generic
@file{ntpkey_iff_alice}
to this file.
To further protect the integrity of the keys,
each file can be encrypted with a secret password.

For the
@code{GQ}
scheme proceed as in the
@code{TC}
scheme to generate keys
and certificates for all group hosts, then for every trusted host
in the group, generate the
@code{IFF}
parameter file.
On trusted host alice run
@code{ntp-keygen}
@code{-T}
@code{-G}
@code{-p} @kbd{password}
to produce her parameter file
@file{ntpkey_GQpar_alice.}@kbd{filestamp},
which includes both server and client keys.
Copy this file to all group hosts and install a soft link
from the generic
@file{ntpkey_gq_alice}
to this file.
In addition, on each host
@kbd{bob}
install a soft link
from generic
@file{ntpkey_gq_}@kbd{bob}
to this file.
As the
@code{GQ}
scheme updates the
@code{GQ}
parameters file and certificate
at the same time, keys and certificates can be regenerated as needed.

For the
@code{MV}
scheme, proceed as in the
@code{TC}
scheme to generate keys
and certificates for all group hosts.
For illustration assume trish is the TA, alice one of several trusted hosts
and bob one of her clients.
On TA trish run
@code{ntp-keygen}
@code{-V} @kbd{n}
@code{-p} @kbd{password},
where
@kbd{n}
is the number of revokable keys (typically 5) to produce
the parameter file
@file{ntpkeys_MVpar_trish.}@kbd{filestamp}
and client key files
@file{ntpkeys_MVkey}@kbd{d} @kbd{_} @file{trish.} @kbd{filestamp}
where
@kbd{d}
is the key number (0 <
@kbd{d}
<
@kbd{n}).
Copy the parameter file to alice and install a soft link
from the generic
@file{ntpkey_mv_alice}
to this file.
Copy one of the client key files to alice for later distribution
to her clients.
It does not matter which client key file goes to alice,
since they all work the same way.
Alice copies the client key file to all of her clients.
On client bob install a soft link from generic
@file{ntpkey_mvkey_bob}
to the client key file.
As the
@code{MV}
scheme is independent of keys and certificates,
these files can be refreshed as needed.

@subsubsection Command Line Options
@table @asis
@item @code{-b} @code{--imbits}= @kbd{modulus}
Set the number of bits in the identity modulus for generating identity keys to
@kbd{modulus}
bits.
The number of bits in the identity modulus defaults to 256, but can be set to
values from 256 to 2048 (32 to 256 octets).
Use the larger moduli with caution, as this can consume considerable computing
resources and increases the size of authenticated packets.
@item @code{-c} @code{--certificate}= @kbd{scheme}
Select certificate signature encryption/message digest scheme.
The
@kbd{scheme}
can be one of the following:
@code{RSA-MD2}, @code{RSA-MD5}, @code{RSA-MDC2}, @code{RSA-SHA}, @code{RSA-SHA1}, @code{RSA-RIPEMD160}, @code{DSA-SHA},
or
@code{DSA-SHA1}.
Note that
@code{RSA}
schemes must be used with an
@code{RSA}
sign key and
@code{DSA}
schemes must be used with a
@code{DSA}
sign key.
The default without this option is
@code{RSA-MD5}.
If compatibility with FIPS 140-2 is required, either the
@code{DSA-SHA}
or
@code{DSA-SHA1}
scheme must be used.
@item @code{-C} @code{--cipher}= @kbd{cipher}
Select the OpenSSL cipher to encrypt the files containing private keys.
The default without this option is three-key triple DES in CBC mode,
@code{des-ede3-cbc}.
The
@code{openssl} @code{-h}
command provided with OpenSSL displays available ciphers.
@item @code{-d} @code{--debug-level}
Increase debugging verbosity level.
This option displays the cryptographic data produced in eye-friendly billboards.
@item @code{-D} @code{--set-debug-level}= @kbd{level}
Set the debugging verbosity to
@kbd{level}.
This option displays the cryptographic data produced in eye-friendly billboards.
@item @code{-e} @code{--id-key}
Write the
@code{IFF}
or
@code{GQ}
public parameters from the
@kbd{IFFkey} @kbd{or} @kbd{GQkey}
client keys file previously specified
as unencrypted data to the standard output stream
@file{stdout}.
This is intended for automatic key distribution by email.
@item @code{-G} @code{--gq-params}
Generate a new encrypted
@code{GQ}
parameters and key file for the Guillou-Quisquater (GQ) identity scheme.
This option is mutually exclusive with the
@code{-I}
and
@code{-V}
options.
@item @code{-H} @code{--host-key}
Generate a new encrypted
@code{RSA}
public/private host key file.
@item @code{-I} @code{--iffkey}
Generate a new encrypted
@code{IFF}
key file for the Schnorr (IFF) identity scheme.
This option is mutually exclusive with the
@code{-G}
and
Fl V
options.
@item @code{-i} @code{--ident}= @kbd{group}
Set the optional Autokey group name to
@kbd{group}.
This is used in the identity scheme parameter file names of
@code{IFF}, @code{GQ},
and
@code{MV}
client parameters files.
In that role, the default is the host name if no group is provided.
The group name, if specified using
@code{-i}
or
@code{-s}
following an
@quoteleft{}@@@quoteright{}
character, is also used in certificate subject and issuer names in the form
@kbd{host} @kbd{@@} @kbd{group}
and should match the group specified via
@code{crypto} @code{ident}
or
@code{server} @code{ident}
in the ntpd configuration file.
@item @code{-l} @code{--lifetime}= @kbd{days}
Set the lifetime for certificate expiration to
@kbd{days}.
The default lifetime is one year (365 days).
@item @code{-m} @code{--modulus}= @kbd{bits}
Set the number of bits in the prime modulus for generating files to
@kbd{bits}.
The modulus defaults to 512, but can be set from 256 to 2048 (32 to 256 octets).
Use the larger moduli with caution, as this can consume considerable computing
resources and increases the size of authenticated packets.
@item @code{-M} @code{--md5key}
Generate a new symmetric keys file containing 10
@code{MD5}
keys, and if OpenSSL is available, 10
@code{SHA}
keys.
An
@code{MD5}
key is a string of 20 random printable ASCII characters, while a
@code{SHA}
key is a string of 40 random hex digits.
The file can be edited using a text editor to change the key type or key content.
This option is mutually exclusive with all other options.
@item @code{-p} @code{--password}= @kbd{passwd}
Set the password for reading and writing encrypted files to
@kbd{passwd}.
These include the host, sign and identify key files.
By default, the password is the string returned by the Unix
@code{hostname}
command.
@item @code{-P} @code{--pvt-cert}
Generate a new private certificate used by the
@code{PC}
identity scheme.
By default, the program generates public certificates.
Note: the PC identity scheme is not recommended for new installations.
@item @code{-q} @code{--export-passwd}= @kbd{passwd}
Set the password for writing encrypted
@code{IFF}, @code{GQ} @code{and} @code{MV}
identity files redirected to
@file{stdout}
to
@kbd{passwd}.
In effect, these files are decrypted with the
@code{-p}
password, then encrypted with the
@code{-q}
password.
By default, the password is the string returned by the Unix
@code{hostname}
command.
@item @code{-s} @code{--subject-key}= @code{[host]} @code{[@@ @kbd{group}]}
Specify the Autokey host name, where
@kbd{host}
is the optional host name and
@kbd{group}
is the optional group name.
The host name, and if provided, group name are used in
@kbd{host} @kbd{@@} @kbd{group}
form as certificate subject and issuer.
Specifying
@code{-s} @code{-@@} @kbd{group}
is allowed, and results in leaving the host name unchanged, as with
@code{-i} @kbd{group}.
The group name, or if no group is provided, the host name are also used in the
file names of
@code{IFF}, @code{GQ},
and
@code{MV}
identity scheme client parameter files.
If
@kbd{host}
is not specified, the default host name is the string returned by the Unix
@code{hostname}
command.
@item @code{-S} @code{--sign-key}= @code{[@code{RSA} | @code{DSA}]}
Generate a new encrypted public/private sign key file of the specified type.
By default, the sign key is the host key and has the same type.
If compatibility with FIPS 140-2 is required, the sign key type must be
@code{DSA}.
@item @code{-T} @code{--trusted-cert}
Generate a trusted certificate.
By default, the program generates a non-trusted certificate.
@item @code{-V} @code{--mv-params} @kbd{nkeys}
Generate
@kbd{nkeys}
encrypted server keys and parameters for the Mu-Varadharajan (MV)
identity scheme.
This option is mutually exclusive with the
@code{-I}
and
@code{-G}
options.
Note: support for this option should be considered a work in progress.
@end table

@subsubsection Random Seed File
All cryptographically sound key generation schemes must have means
to randomize the entropy seed used to initialize
the internal pseudo-random number generator used
by the library routines.
The OpenSSL library uses a designated random seed file for this purpose.
The file must be available when starting the NTP daemon and
@code{ntp-keygen}
program.
If a site supports OpenSSL or its companion OpenSSH,
it is very likely that means to do this are already available.

It is important to understand that entropy must be evolved
for each generation, for otherwise the random number sequence
would be predictable.
Various means dependent on external events, such as keystroke intervals,
can be used to do this and some systems have built-in entropy sources.
Suitable means are described in the OpenSSL software documentation,
but are outside the scope of this page.

The entropy seed used by the OpenSSL library is contained in a file,
usually called
@file{.rnd},
which must be available when starting the NTP daemon
or the
@code{ntp-keygen}
program.
The NTP daemon will first look for the file
using the path specified by the
@code{randfile}
subcommand of the
@code{crypto}
configuration command.
If not specified in this way, or when starting the
@code{ntp-keygen}
program,
the OpenSSL library will look for the file using the path specified
by the
.Ev RANDFILE
environment variable in the user home directory,
whether root or some other user.
If the
.Ev RANDFILE
environment variable is not present,
the library will look for the
@file{.rnd}
file in the user home directory.
Since both the
@code{ntp-keygen}
program and
@code{ntpd(1ntpdmdoc)}
daemon must run as root, the logical place to put this file is in
@file{/.rnd}
or
@file{/root/.rnd}.
If the file is not available or cannot be written,
the daemon exits with a message to the system log and the program
exits with a suitable error message.

@subsubsection Cryptographic Data Files
All file formats begin with two nonencrypted lines.
The first line contains the file name, including the generated host name
and filestamp, in the format
@file{ntpkey_}@kbd{key} @kbd{_} @kbd{name}. @kbd{filestamp},
where
@kbd{key}
is the key or parameter type,
@kbd{name}
is the host or group name and
@kbd{filestamp}
is the filestamp (NTP seconds) when the file was created.
By convention,
@kbd{key}
names in generated file names include both upper and lower case
characters, while
@kbd{key}
names in generated link names include only lower case characters.
The filestamp is not used in generated link names.
The second line contains the datestamp in conventional Unix
@file{date}
format.
Lines beginning with
@quoteleft{}#@quoteright{}
are considered comments and ignored by the
@code{ntp-keygen}
program and
@code{ntpd(1ntpdmdoc)}
daemon.

The remainder of the file contains cryptographic data, encoded first using ASN.1
rules, then encrypted if necessary, and finally written in PEM-encoded
printable ASCII text, preceded and followed by MIME content identifier lines.

The format of the symmetric keys file, ordinarily named
@file{ntp.keys},
is somewhat different than the other files in the interest of backward compatibility.
Ordinarily, the file is generated by this program, but it can be constructed
and edited using an ordinary text editor.
@verbatim
# ntpkey_MD5key_bk.ntp.org.3595864945
# Thu Dec 12 19:22:25 2013

1  MD5 L";Nw<\`.I<f4U0)247"i  # MD5 key
2  MD5 &>l0%XXK9O'51VwV<xq~  # MD5 key
3  MD5 lb4zLW~d^!K:]RsD'qb6  # MD5 key
4  MD5 Yue:tL[+vR)M\`n~bY,'?  # MD5 key
5  MD5 B;fx'Kgr/&4ZTbL6=RxA  # MD5 key
6  MD5 4eYwa\`o@}3i@@@@V@@..R9!l  # MD5 key
7  MD5 \`A.([h+;wTQ|xfi%Sn_!  # MD5 key
8  MD5 45:V,r4]l6y^JH6"Sh?F  # MD5 key
9  MD5 3-5vcn*6l29DS?Xdsg)*  # MD5 key
10 MD5 2late4Me              # MD5 key
11 SHA1 a27872d3030a9025b8446c751b4551a7629af65c  # SHA1 key
12 SHA1 21bc3b4865dbb9e920902abdccb3e04ff97a5e74  # SHA1 key
13 SHA1 2b7736fe24fef5ba85ae11594132ab5d6f6daba9  # SHA1 key
14 SHA  a5332809c8878dd3a5b918819108a111509aeceb  # SHA  key
15 MD2  2fe16c88c760ff2f16d4267e36c1aa6c926e6964  # MD2  key
16 MD4  b2691811dc19cfc0e2f9bcacd74213f29812183d  # MD4  key
17 MD5  e4d6735b8bdad58ec5ffcb087300a17f7fef1f7c  # MD5  key
18 MDC2 a8d5e2315c025bf3a79174c87fbd10477de2eabc  # MDC2 key
19 RIPEMD160 77ca332cafb30e3cafb174dcd5b80ded7ba9b3d2  # RIPEMD160 key
20 AES128CMAC f92ff73eee86c1e7dc638d6489a04e4e555af878  # AES128CMAC key
@end verbatim
@example
Figure 1. Typical Symmetric Key File
@end example

Figure 1 shows a typical symmetric keys file used by the reference
implementation.
Following the header the keys are entered one per line in the format
@example
@kbd{keyno} @kbd{type} @kbd{key}
@end example
where
@kbd{keyno}
is a positive integer in the range 1-65535;
@kbd{type}
is the key type for the message digest algorithm, which in the absence of the
OpenSSL library must be
@code{MD5}
to designate the MD5 message digest algorithm;
if the OpenSSL library is installed, the key type can be any
message digest algorithm supported by that library;
however, if compatibility with FIPS 140-2 is required,
the key type must be either
@code{SHA}
or
@code{SHA1};
@kbd{key}
is the key itself,
which is a printable ASCII string 20 characters or less in length:
each character is chosen from the 93 printable characters
in the range 0x21 through 0x7e (
@quoteleft{}@quoteright{}!
through
@quoteleft{}~@quoteright{}
) excluding space and the
@quoteleft{}#@quoteright{}
character, and terminated by whitespace or a
@quoteleft{}#@quoteright{}
character.
An OpenSSL key consists of a hex-encoded ASCII string of 40 characters, which
is truncated as necessary.

Note that the keys used by the
@code{ntpq(1ntpqmdoc)}
and
@code{ntpdc(1ntpdcmdoc)}
programs
are checked against passwords requested by the programs
and entered by hand, so it is generally appropriate to specify these keys
in human readable ASCII format.

The
@code{ntp-keygen}
program generates a symmetric keys file
@file{ntpkey_MD5key_}@kbd{hostname}. @kbd{filestamp}.
Since the file contains private shared keys,
it should be visible only to root and distributed by secure means
to other subnet hosts.
The NTP daemon loads the file
@file{ntp.keys},
so
@code{ntp-keygen}
installs a soft link from this name to the generated file.
Subsequently, similar soft links must be installed by manual
or automated means on the other subnet hosts.
While this file is not used with the Autokey Version 2 protocol,
it is needed to authenticate some remote configuration commands
used by the
@code{ntpq(1ntpqmdoc)}
and
@code{ntpdc(1ntpdcmdoc)}
utilities.

This section was generated by @strong{AutoGen},
using the @code{agtexi-cmd} template and the option descriptions for the @code{ntp-keygen} program.
This software is released under the NTP license, <http://ntp.org/license>.

@menu
* ntp-keygen usage::                  ntp-keygen help/usage (@option{--help})
* ntp-keygen imbits::                 imbits option (-b)
* ntp-keygen certificate::            certificate option (-c)
* ntp-keygen cipher::                 cipher option (-C)
* ntp-keygen id-key::                 id-key option (-e)
* ntp-keygen gq-params::              gq-params option (-G)
* ntp-keygen host-key::               host-key option (-H)
* ntp-keygen iffkey::                 iffkey option (-I)
* ntp-keygen ident::                  ident option (-i)
* ntp-keygen lifetime::               lifetime option (-l)
* ntp-keygen modulus::                modulus option (-m)
* ntp-keygen md5key::                 md5key option (-M)
* ntp-keygen pvt-cert::               pvt-cert option (-P)
* ntp-keygen password::               password option (-p)
* ntp-keygen export-passwd::          export-passwd option (-q)
* ntp-keygen subject-name::           subject-name option (-s)
* ntp-keygen sign-key::               sign-key option (-S)
* ntp-keygen trusted-cert::           trusted-cert option (-T)
* ntp-keygen mv-params::              mv-params option (-V)
* ntp-keygen mv-keys::                mv-keys option (-v)
* ntp-keygen config::                 presetting/configuring ntp-keygen
* ntp-keygen exit status::            exit status
* ntp-keygen Usage::                  Usage
* ntp-keygen Notes::                  Notes
* ntp-keygen Bugs::                   Bugs
@end menu

@node ntp-keygen usage
@subsection ntp-keygen help/usage (@option{--help})
@cindex ntp-keygen help

This is the automatically generated usage text for ntp-keygen.

The text printed is the same whether selected with the @code{help} option
(@option{--help}) or the @code{more-help} option (@option{--more-help}).  @code{more-help} will print
the usage text by passing it through a pager program.
@code{more-help} is disabled on platforms without a working
@code{fork(2)} function.  The @code{PAGER} environment variable is
used to select the program, defaulting to @file{more}.  Both will exit
with a status code of 0.

@exampleindent 0
@example
ntp-keygen (ntp) - Create a NTP host key - Ver. 4.2.8p13
Usage:  ntp-keygen [ -<flag> [<val>] | --<name>[@{=| @}<val>] ]...
  Flg Arg Option-Name    Description
   -b Num imbits         identity modulus bits
                                - it must be in the range:
                                  256 to 2048
   -c Str certificate    certificate scheme
   -C Str cipher         privatekey cipher
   -d no  debug-level    Increase debug verbosity level
                                - may appear multiple times
   -D Num set-debug-level Set the debug verbosity level
                                - may appear multiple times
   -e no  id-key         Write IFF or GQ identity keys
   -G no  gq-params      Generate GQ parameters and keys
   -H no  host-key       generate RSA host key
   -I no  iffkey         generate IFF parameters
   -i Str ident          set Autokey group name
   -l Num lifetime       set certificate lifetime
   -m Num modulus        prime modulus
                                - it must be in the range:
                                  256 to 2048
   -M no  md5key         generate symmetric keys
   -P no  pvt-cert       generate PC private certificate
   -p Str password       local private password
   -q Str export-passwd  export IFF or GQ group keys with password
   -s Str subject-name   set host and optionally group name
   -S Str sign-key       generate sign key (RSA or DSA)
   -T no  trusted-cert   trusted certificate (TC scheme)
   -V Num mv-params      generate <num> MV parameters
   -v Num mv-keys        update <num> MV keys
      opt version        output version information and exit
   -? no  help           display extended usage information and exit
   -! no  more-help      extended usage information passed thru pager
   -> opt save-opts      save the option state to a config file
   -< Str load-opts      load options from a config file
                                - disabled as '--no-load-opts'
                                - may appear multiple times

Options are specified by doubled hyphens and their name or by a single
hyphen and the flag character.


The following option preset mechanisms are supported:
 - reading file $HOME/.ntprc
 - reading file ./.ntprc
 - examining environment variables named NTP_KEYGEN_*

Please send bug reports to:  <http://bugs.ntp.org, bugs@@ntp.org>
@end example
@exampleindent 4

@node ntp-keygen imbits
@subsection imbits option (-b)
@cindex ntp-keygen-imbits

This is the ``identity modulus bits'' option.
This option takes a number argument @file{imbits}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

The number of bits in the identity modulus.  The default is 256.
@node ntp-keygen certificate
@subsection certificate option (-c)
@cindex ntp-keygen-certificate

This is the ``certificate scheme'' option.
This option takes a string argument @file{scheme}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

scheme is one of
RSA-MD2, RSA-MD5, RSA-MDC2, RSA-SHA, RSA-SHA1, RSA-RIPEMD160,
DSA-SHA, or DSA-SHA1.

Select the certificate signature encryption/message digest scheme.
Note that RSA schemes must be used with a RSA sign key and DSA
schemes must be used with a DSA sign key.  The default without
this option is RSA-MD5.
@node ntp-keygen cipher
@subsection cipher option (-C)
@cindex ntp-keygen-cipher

This is the ``privatekey cipher'' option.
This option takes a string argument @file{cipher}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Select the cipher which is used to encrypt the files containing
private keys.  The default is three-key triple DES in CBC mode,
equivalent to "@code{-C des-ede3-cbc}".  The openssl tool lists ciphers
available in "@code{openssl -h}" output.
@node ntp-keygen id-key
@subsection id-key option (-e)
@cindex ntp-keygen-id-key

This is the ``write iff or gq identity keys'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Write the public parameters from the IFF or GQ client keys to
the standard output.
This is intended for automatic key distribution by email.
@node ntp-keygen gq-params
@subsection gq-params option (-G)
@cindex ntp-keygen-gq-params

This is the ``generate gq parameters and keys'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate parameters and keys for the GQ identification scheme,
obsoleting any that may exist.
@node ntp-keygen host-key
@subsection host-key option (-H)
@cindex ntp-keygen-host-key

This is the ``generate rsa host key'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate new host keys, obsoleting any that may exist.
@node ntp-keygen iffkey
@subsection iffkey option (-I)
@cindex ntp-keygen-iffkey

This is the ``generate iff parameters'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate parameters for the IFF identification scheme, obsoleting
any that may exist.
@node ntp-keygen ident
@subsection ident option (-i)
@cindex ntp-keygen-ident

This is the ``set autokey group name'' option.
This option takes a string argument @file{group}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Set the optional Autokey group name to name.  This is used in
the file name of IFF, GQ, and MV client parameters files.  In
that role, the default is the host name if this option is not
provided.  The group name, if specified using @code{-i/--ident} or
using @code{-s/--subject-name} following an '@code{@@}' character,
is also a part of the self-signed host certificate subject and
issuer names in the form @code{host@@group} and should match the
'@code{crypto ident}' or '@code{server ident}' configuration in the
@code{ntpd} configuration file.
@node ntp-keygen lifetime
@subsection lifetime option (-l)
@cindex ntp-keygen-lifetime

This is the ``set certificate lifetime'' option.
This option takes a number argument @file{lifetime}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Set the certificate expiration to lifetime days from now.
@node ntp-keygen modulus
@subsection modulus option (-m)
@cindex ntp-keygen-modulus

This is the ``prime modulus'' option.
This option takes a number argument @file{modulus}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

The number of bits in the prime modulus.  The default is 512.
@node ntp-keygen md5key
@subsection md5key option (-M)
@cindex ntp-keygen-md5key

This is the ``generate symmetric keys'' option.
Generate symmetric keys, obsoleting any that may exist.
@node ntp-keygen pvt-cert
@subsection pvt-cert option (-P)
@cindex ntp-keygen-pvt-cert

This is the ``generate pc private certificate'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate a private certificate.  By default, the program generates
public certificates.
@node ntp-keygen password
@subsection password option (-p)
@cindex ntp-keygen-password

This is the ``local private password'' option.
This option takes a string argument @file{passwd}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Local files containing private data are encrypted with the
DES-CBC algorithm and the specified password.  The same password
must be specified to the local ntpd via the "crypto pw password"
configuration command.  The default password is the local
hostname.
@node ntp-keygen export-passwd
@subsection export-passwd option (-q)
@cindex ntp-keygen-export-passwd

This is the ``export iff or gq group keys with password'' option.
This option takes a string argument @file{passwd}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Export IFF or GQ identity group keys to the standard output,
encrypted with the DES-CBC algorithm and the specified password.
The same password must be specified to the remote ntpd via the
"crypto pw password" configuration command.  See also the option
--id-key (-e) for unencrypted exports.
@node ntp-keygen subject-name
@subsection subject-name option (-s)
@cindex ntp-keygen-subject-name

This is the ``set host and optionally group name'' option.
This option takes a string argument @file{host@@group}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Set the Autokey host name, and optionally, group name specified
following an '@code{@@}' character.  The host name is used in the file
name of generated host and signing certificates, without the
group name.  The host name, and if provided, group name are used
in @code{host@@group} form for the host certificate subject and issuer
fields.  Specifying '@code{-s @@group}' is allowed, and results in
leaving the host name unchanged while appending @code{@@group} to the
subject and issuer fields, as with @code{-i group}.  The group name, or
if not provided, the host name are also used in the file names
of IFF, GQ, and MV client parameter files.
@node ntp-keygen sign-key
@subsection sign-key option (-S)
@cindex ntp-keygen-sign-key

This is the ``generate sign key (rsa or dsa)'' option.
This option takes a string argument @file{sign}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate a new sign key of the designated type, obsoleting any
that may exist.  By default, the program uses the host key as the
sign key.
@node ntp-keygen trusted-cert
@subsection trusted-cert option (-T)
@cindex ntp-keygen-trusted-cert

This is the ``trusted certificate (tc scheme)'' option.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate a trusted certificate.  By default, the program generates
a non-trusted certificate.
@node ntp-keygen mv-params
@subsection mv-params option (-V)
@cindex ntp-keygen-mv-params

This is the ``generate <num> mv parameters'' option.
This option takes a number argument @file{num}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

Generate parameters and keys for the Mu-Varadharajan (MV)
identification scheme.
@node ntp-keygen mv-keys
@subsection mv-keys option (-v)
@cindex ntp-keygen-mv-keys

This is the ``update <num> mv keys'' option.
This option takes a number argument @file{num}.

@noindent
This option has some usage constraints.  It:
@itemize @bullet
@item
must be compiled in by defining @code{AUTOKEY} during the compilation.
@end itemize

This option has no @samp{doc} documentation.


@node ntp-keygen config
@subsection presetting/configuring ntp-keygen

Any option that is not marked as @i{not presettable} may be preset by
loading values from configuration ("rc" or "ini") files, and values from environment variables named @code{NTP-KEYGEN} and @code{NTP-KEYGEN_<OPTION_NAME>}.  @code{<OPTION_NAME>} must be one of
the options listed above in upper case and segmented with underscores.
The @code{NTP-KEYGEN} variable will be tokenized and parsed like
the command line.  The remaining variables are tested for existence and their
values are treated like option arguments.


@noindent
@code{libopts} will search in 2 places for configuration files:
@itemize @bullet
@item
$HOME
@item
$PWD
@end itemize
The environment variables @code{HOME}, and @code{PWD}
are expanded and replaced when @file{ntp-keygen} runs.
For any of these that are plain files, they are simply processed.
For any that are directories, then a file named @file{.ntprc} is searched for
within that directory and processed.

Configuration files may be in a wide variety of formats.
The basic format is an option name followed by a value (argument) on the
same line.  Values may be separated from the option name with a colon,
equal sign or simply white space.  Values may be continued across multiple
lines by escaping the newline with a backslash.

Multiple programs may also share the same initialization file.
Common options are collected at the top, followed by program specific
segments.  The segments are separated by lines like:
@example
[NTP-KEYGEN]
@end example
@noindent
or by
@example
<?program ntp-keygen>
@end example
@noindent
Do not mix these styles within one configuration file.

Compound values and carefully constructed string values may also be
specified using XML syntax:
@example
<option-name>
   <sub-opt>...&lt;...&gt;...</sub-opt>
</option-name>
@end example
@noindent
yielding an @code{option-name.sub-opt} string value of
@example
"...<...>..."
@end example
@code{AutoOpts} does not track suboptions.  You simply note that it is a
hierarchicly valued option.  @code{AutoOpts} does provide a means for searching
the associated name/value pair list (see: optionFindValue).

The command line options relating to configuration and/or usage help are:

@subsubheading version (-)

Print the program version to standard out, optionally with licensing
information, then exit 0.  The optional argument specifies how much licensing
detail to provide.  The default is to print just the version.  The licensing infomation may be selected with an option argument.
Only the first letter of the argument is examined:

@table @samp
@item version
Only print the version.  This is the default.
@item copyright
Name the copyright usage licensing terms.
@item verbose
Print the full copyright usage licensing terms.
@end table

@node ntp-keygen exit status
@subsection ntp-keygen exit status

One of the following exit values will be returned:
@table @samp
@item 0 (EXIT_SUCCESS)
Successful program execution.
@item 1 (EXIT_FAILURE)
The operation failed or the command syntax was not valid.
@item 66 (EX_NOINPUT)
A specified configuration file could not be loaded.
@item 70 (EX_SOFTWARE)
libopts had an internal operational error.  Please report
it to autogen-users@@lists.sourceforge.net.  Thank you.
@end table
@node ntp-keygen Usage
@subsection ntp-keygen Usage
@node ntp-keygen Notes
@subsection ntp-keygen Notes
@node ntp-keygen Bugs
@subsection ntp-keygen Bugs
