#
# Makefile for the Linux/SuperH CPU-specifc IRQ handlers.
#
obj-y	+= imask.o

obj-$(CONFIG_CPU_HAS_IPR_IRQ)		+= ipr.o
obj-$(CONFIG_CPU_HAS_PINT_IRQ)		+= pint.o 
obj-$(CONFIG_CPU_HAS_MASKREG_IRQ)	+= maskreg.o
obj-$(CONFIG_CPU_HAS_INTC_IRQ)		+= intc.o
obj-$(CONFIG_CPU_HAS_INTC2_IRQ)		+= intc2.o
