#
# Makefile for the virtual sub-component of DAL.
# It provides the control and status of HW CRTC block.

VIRTUAL = virtual_link_encoder.o virtual_stream_encoder.o

AMD_DAL_VIRTUAL = $(addprefix $(AMDDALPATH)/dc/virtual/,$(VIRTUAL))

AMD_DISPLAY_FILES += $(AMD_DAL_VIRTUAL)
