# arch/arm/mach-s3c6400/Makefile
#
# Copyright 2008 Openmoko, Inc.
# Copyright 2008 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

# Core support for S3C6400 system

obj-n				+= blank.o

# Machine support

obj-$(CONFIG_MACH_SMDK6400)	+= mach-smdk6400.o
