.\" $OpenBSD: omdog.4,v 1.4 2016/06/26 05:16:33 jsg Exp $
.\" Copyright (c) 2014 Raphael Graf <rapha@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: June 26 2016 $
.Dt OMDOG 4 armv7
.Os
.Sh NAME
.Nm omdog
.Nd Texas Instruments watchdog timer device
.Sh SYNOPSIS
.Cd "omdog* at fdt?"
.Sh DESCRIPTION
The
.Nm
driver provides support for the watchdog timer device integrated in OMAP and
AM335X SoCs.
.Sh HISTORY
The
.Nm
device driver first appeared in
.Ox 5.4 .
.Sh AUTHORS
The
.Nm
driver was written by
.An Dale Rahn Aq Mt drahn@dalerahn.com .
