#!/bin/sh -
#
# $NetBSD: zforce,v 1.2 2003/12/28 12:43:43 wiz Exp $
# $OpenBSD: zforce,v 1.2 2003/08/05 18:22:17 deraadt Exp $
#
#-
# Copyright (c) 2003 Otto Moerbeek <otto@drijf.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# $FreeBSD$
prog=`basename $0`
USAGE="usage: $prog file ..."
if test $# -eq 0; then
	echo $USAGE
	exit 1
fi

ret=0

while test $# -ne 0; do
	case "$1" in
		*[._-]gz)
			shift
			;;
		*.t[ag]z)
			shift
			;;
		*)
			if file "$1" |
				grep -q "gzip compressed data" 2> /dev/null
			then
				n="$1".gz
				if mv "$1" "$n" 2> /dev/null; then
					echo "$1" -- renamed to "$n"
				else
					ret=1
					echo $prog: cannot rename "$1" to "$n"
				fi
			fi
			shift
			;;
	esac
done
exit $ret
