obj-$(CONFIG_RK29_SUPPORT_MODEM)              += rk29_modem.o

obj-$(CONFIG_MODEM_ROCKCHIP_DEMO)		+=modem_rockchip_demo.o

obj-$(CONFIG_MODEM_ZTE_MG3732)			+=modem_zte_mg3732.o

#obj-$(CONFIG_MODEM_ZTE_MF210)                   	+= modem_zte_mf210.o
#obj-$(CONFIG_MODEM_ZTE_AD3812)                 += modem_zte_ad3812.o
#obj-$(CONFIG_MODEM_THINKWILL_ME800)	+= modem_thinkwill_me800.o
#obj-$(CONFIG_MODEM_HUAWEI_EM660)		+= modem_huawei_em660.o
#obj-$(CONFIG_MODEM_HUAWEI_EM770)		+= modem_huawei_em770.o
#obj-$(CONFIG_MODEM_HUAWEI_EM660C)	+= modem_huawei_em660c.o
#obj-$(CONFIG_MODEM_ZTE_MU301)			+= modem_zte_mu301.o
#obj-$(CONFIG_MODEM_TDM_330)			+= modem_tdm_330.o


