obj-$(CONFIG_ROCKCHIP_MPP_SERVICE) += mpp_service.o
obj-$(CONFIG_ROCKCHIP_MPP_DEVICE) += mpp_dev_rkvenc.o mpp_dev_vepu.o \
	mpp_dev_h265e.o mpp_dev_common.o vpu_iommu_drm.o vpu_iommu_ion.o \
	vpu_iommu_ops.o
