#
# Makefile for the linux kernel.
#

obj-y			:= common.o setup.o irq.o pci.o time.o
obj-m			:=
obj-n			:=
obj-			:=

obj-$(CONFIG_ARCH_IQ80321) += iq80321-mm.o iq80321-pci.o
obj-$(CONFIG_ARCH_IQ31244) += iq31244-mm.o iq31244-pci.o
