# ex:ts=8
#
# Makefile for amd
# 	This file is under a "BSD" copyright (c) by David O'Brien 1998
#
# $FreeBSD$

SUBDIR= include libamu .WAIT \
	amd amq fixmount fsinfo hlfsd mk-amd-map pawd \
	scripts wire-test
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
