# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile - Intel MIC Linux driver.
# Copyright(c) 2016, Intel Corporation.
#
obj-$(CONFIG_VOP) := vop.o

vop-objs += vop_main.o
vop-objs += vop_debugfs.o
vop-objs += vop_vringh.o
