# SPDX-License-Identifier: GPL-2.0-only
kcov-flags-y					+= -fsanitize-coverage=trace-pc
kcov-flags-$(CONFIG_KCOV_ENABLE_COMPARISONS)	+= -fsanitize-coverage=trace-cmp

export CFLAGS_KCOV := $(kcov-flags-y)
