nvhost-objs = \
	nvhost_acm.o \
	nvhost_syncpt.o \
	nvhost_cdma.o \
	nvhost_cpuaccess.o \
	nvhost_intr.o \
	nvhost_channel.o \
	nvhost_3dctx.o \
	dev.o \
	bus.o \
	debug.o

obj-$(CONFIG_TEGRA_GRHOST) += nvhost.o
