include $(top_srcdir)/scripts/subarch.include
ARCH ?= $(SUBARCH)

LIBLIVEUPDATE_SRCDIR := $(selfdir)/liveupdate/lib

LIBLIVEUPDATE_C := lu_utils.c

LIBLIVEUPDATE_OUTPUT := $(OUTPUT)/libliveupdate

LIBLIVEUPDATE_O := $(patsubst %.c, $(LIBLIVEUPDATE_OUTPUT)/%.o, $(LIBLIVEUPDATE_C))

CFLAGS += -I$(LIBLIVEUPDATE_SRCDIR)/include

$(LIBLIVEUPDATE_OUTPUT):
	$(Q)mkdir -p $@

$(LIBLIVEUPDATE_O): $(LIBLIVEUPDATE_OUTPUT)/%.o : $(LIBLIVEUPDATE_SRCDIR)/%.c | $(LIBLIVEUPDATE_OUTPUT)
	$(CC) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c $< -o $@

EXTRA_CLEAN += $(LIBLIVEUPDATE_OUTPUT)
