# SPDX-License-Identifier: GPL-2.0
# Nuvoton pinctrl support

obj-$(CONFIG_PINCTRL_WPCM450)	+= pinctrl-wpcm450.o
obj-$(CONFIG_PINCTRL_NPCM7XX)	+= pinctrl-npcm7xx.o
obj-$(CONFIG_PINCTRL_NPCM8XX)	+= pinctrl-npcm8xx.o
obj-$(CONFIG_PINCTRL_MA35)	+= pinctrl-ma35.o
obj-$(CONFIG_PINCTRL_MA35D1)	+= pinctrl-ma35d1.o
