obj-$(CONFIG_RK_PM_TESTS) += rk_pm_tests.o

# Optional functions
obj-$(CONFIG_PM_TEST_CLK_RATE) += clk_rate.o
obj-$(CONFIG_PM_TEST_CLK_VOLT) += clk_volt.o
obj-$(CONFIG_PM_TEST_FREQ_LIMIT) += freq_limit.o
obj-$(CONFIG_PM_TEST_CPU_USAGE) += cpu_usage.o

