# SPDX-License-Identifier: GPL-2.0-or-later
#
# AMD Address Translation Library Makefile
#
# Copyright (c) 2023, Advanced Micro Devices, Inc.
# All Rights Reserved.
#
# Author: Yazen Ghannam <Yazen.Ghannam@amd.com>

amd_atl-y		:= access.o
amd_atl-y		+= core.o
amd_atl-y		+= dehash.o
amd_atl-y		+= denormalize.o
amd_atl-y		+= map.o
amd_atl-y		+= system.o
amd_atl-y		+= umc.o

obj-$(CONFIG_AMD_ATL)	+= amd_atl.o
