# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_INTEL_SOCFPGA) += \
	socfpga_arria5_socdk.dtb \
	socfpga_arria10_chameleonv3.dtb \
	socfpga_arria10_mercury_pe1.dtb \
	socfpga_arria10_socdk_nand.dtb \
	socfpga_arria10_socdk_qspi.dtb \
	socfpga_arria10_socdk_sdmmc.dtb \
	socfpga_cyclone5_chameleon96.dtb \
	socfpga_cyclone5_mcvevk.dtb \
	socfpga_cyclone5_socdk.dtb \
	socfpga_cyclone5_de0_nano_soc.dtb \
	socfpga_cyclone5_de10nano.dtb \
	socfpga_cyclone5_sockit.dtb \
	socfpga_cyclone5_socrates.dtb \
	socfpga_cyclone5_sodia.dtb \
	socfpga_cyclone5_vining_fpga.dtb \
	socfpga_vt.dtb
