.\" Copyright (c) 2008 Isilon Inc http://www.isilon.com/
.\" Authors: Doug Rabson <dfr@rabson.org>
.\" Developed with Red Inc: Alfred Perlstein <alfred@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.Dd January 26, 2010
.Dt RPC_GSS_GET_PRINCIPAL_NAME 3
.Os
.Sh NAME
.Nm rpc_gss_get_principal_name
.Nd "Get a principal name"
.Sh LIBRARY
.Lb librpcsec_gss
.Sh SYNOPSIS
.In rpc/rpcsec_gss.h
.Ft bool_t
.Fo rpc_gss_get_principal_name
.Fa "rpc_gss_principal_t *principal"
.Fa "const char *mech"
.Fa "const char *name"
.Fa "const char *node"
.Fa "const char *domain"
.Fc
.Sh DESCRIPTION
This function can be used to generate a client principal name from
various strings.
.Sh PARAMETERS
.Bl -tag -width ".It principal"
.It principal
If the principal is created successfully,
.Fa *principal
will be set to point at the new principal in GSS-API exported name form
.It mech
The name of the mechanism for this principal
.It name
The name part of the principal
.It node
If non-null, the hostname or instance part of the principal
.It domain
If non-null, the domain or realm part of the principal
.El
.Sh RETURN VALUES
Returns
.Dv TRUE
if the principal was created or
.Dv FALSE
otherwise
.Sh SEE ALSO
.Xr gss_export_name 3 ,
.Xr gssapi 3 ,
.Xr rpc 3 ,
.Xr rpcset_gss 3
.Sh HISTORY
The
.Nm
function first appeared in
.Fx 8.0 .
.Sh AUTHORS
This
manual page was written by
.An Doug Rabson Aq Mt dfr@FreeBSD.org .
