#
# Specific board support, not covered by a mach group.
#
obj-$(CONFIG_SH_MAGIC_PANEL_R2)	+= board-magicpanelr2.o
obj-$(CONFIG_SH_SECUREEDGE5410)	+= board-secureedge5410.o
obj-$(CONFIG_SH_SH2007)		+= board-sh2007.o
obj-$(CONFIG_SH_SH7785LCR)	+= board-sh7785lcr.o
obj-$(CONFIG_SH_URQUELL)	+= board-urquell.o
obj-$(CONFIG_SH_SHMIN)		+= board-shmin.o
obj-$(CONFIG_SH_EDOSK7705)	+= board-edosk7705.o
obj-$(CONFIG_SH_EDOSK7760)	+= board-edosk7760.o
obj-$(CONFIG_SH_ESPT)		+= board-espt.o
obj-$(CONFIG_SH_POLARIS)	+= board-polaris.o
obj-$(CONFIG_SH_TITAN)		+= board-titan.o
obj-$(CONFIG_SH_SH7757LCR)	+= board-sh7757lcr.o
