.\"	$OpenBSD: acpivideo.4,v 1.6 2020/04/06 00:01:08 pirofti Exp $
.\"
.\" Copyright (c) 2009 Paul Irofti <paul@irofti.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"
.Dd $Mdocdate: April 6 2020 $
.Dt ACPIVIDEO 4
.Os
.Sh NAME
.Nm acpivideo
.Nd ACPI video
.Sh SYNOPSIS
.Cd "acpivideo* at acpi?"
.Sh DESCRIPTION
The
.Nm
driver supports ACPI display output switching and brightness control.
Output displays can take the form of CRTs, LCDs, TV-OUTs or any similar devices
that may be connected to the machine.
.Sh SEE ALSO
.Xr acpi 4 ,
.Xr acpithinkpad 4 ,
.Xr acpitoshiba 4 ,
.Xr acpivout 4 ,
.Xr intro 4
.Sh HISTORY
The
.Nm
driver first appeared in
.Ox 4.6 .
.Sh AUTHORS
.An -nosplit
The
.Nm
driver was written by
.An Federico G. Schwindt Aq Mt fgsch@openbsd.org
and
.An Paul Irofti Aq Mt paul@irofti.net .
.Sh CAVEATS
On IBM and Lenovo ThinkPad systems,
.Nm
functionality is handled by the
.Xr acpithinkpad 4
driver.
