.\"	$OpenBSD: vgafb.4,v 1.4 2018/04/23 06:24:33 jmc Exp $
.\"
.\" Copyright (c) 2002 Jason L. Wright (jason@thought.net)
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
.\" ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd $Mdocdate: April 23 2018 $
.Dt VGAFB 4
.Os
.Sh NAME
.Nm vgafb
.Nd VGA frame buffer
.Sh SYNOPSIS
.Cd # sparc64, macppc
.Cd "vgafb* at pci?"
.Cd "wsdisplay* at vgafb?"
.Sh DESCRIPTION
The
.Nm
is a memory based color frame buffer driver for the
.Xr wscons 4
console framework.
It does not provide direct device driver entry points
but makes its functions available via the internal
.Xr wsdisplay 4
interface.
Both unaccelerated access as a dumb framebuffer and
accelerated access methods are provided to
.Xr wscons 4 .
.Sh SEE ALSO
.Xr intro 4 ,
.Xr pci 4 ,
.Xr wscons 4 ,
.Xr wsdisplay 4
