#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: mountlate
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="mountlate"
desc="Mount filesystems with \"late\" option from /etc/fstab"
start_cmd="mountlate_start"
stop_cmd=":"

mountlate_start()
{
	local err latefs

	# Mount "late" filesystems.
	#
	err=0
	echo -n 'Mounting late filesystems:'
	mount -a -L
	err=$?
	echo '.'

	case ${err} in
	0)
		;;
	*)
		echo 'Mounting /etc/fstab filesystems failed,' \
		    ' startup aborted'
		stop_boot true
		;;
	esac

 	# If we booted a special kernel remove the record
 	# so we will boot the default kernel next time.
 	if [ -x /sbin/nextboot ]; then
		/sbin/nextboot -D
 	fi
}

load_rc_config $name
run_rc_command "$1"
