#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: zfsd
# REQUIRE: devd zfs
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="zfsd"
rcvar="zfsd_enable"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
