#!/bin/sh
# $Id: fselect2,v 1.8 2010/01/13 10:20:03 tom Exp $

. ./setup-vars

exec 3>&1
RESULT=`$DIALOG --title "Please choose a file" "$@" --fselect $HOME/ 0 0 2>&1 1>&3`
retval=$?
exec 3>&-

. ./report-string
