.\"	$OpenBSD: ieee80211_crypto.9,v 1.6 2015/11/23 17:53:57 jmc Exp $
.\"
.\" Copyright (c) 2004 Bruce M. Simpson <bms@spc.org>
.\" Copyright (c) 2004 Darron Broad <darron@kewl.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD: src/share/man/man9/ieee80211_crypto.9,v 1.2 2004/07/07 12:59:39 ru Exp $
.\" $Id: ieee80211_crypto.9,v 1.6 2015/11/23 17:53:57 jmc Exp $
.\"
.Dd $Mdocdate: November 23 2015 $
.Dt IEEE80211_CRYPTO_ATTACH 9
.Os
.Sh NAME
.Nm ieee80211_crypto_attach , ieee80211_crypto_detach , ieee80211_wep_crypt
.Nd 802.11 WEP encryption functions
.Sh SYNOPSIS
.Ft void
.Fn ieee80211_crypto_attach "struct ifnet *ifp"
.Ft void
.Fn ieee80211_crypto_detach "struct ifnet *ifp"
.Ft struct mbuf *
.Fn ieee80211_wep_crypt "struct ifnet *ifp" "struct mbuf *m0" "int txflag"
.Sh DESCRIPTION
These functions provide software encryption support
for 802.11 device drivers.
.Pp
.\"
The
.Fn ieee80211_crypto_attach
function initializes crypto support for the interface
.Fa ifp ,
and sets the initialization vector (IV) for WEP encryption to
a random number derived from a secure PRNG.
.Pp
.\"
The
.Fn ieee80211_crypto_detach
function frees data structures associated with crypto support
for the interface
.Fa ifp .
.Pp
.\"
The
.Fn ieee80211_wep_crypt
function runs the appropriate WEP encryption algorithm over the 802.11
encapsulated frame held in the mbuf chain
.Fa m0 ,
for transmission or reception on the interface
.Fa ifp .
The
.Fa txflag
argument specifies whether the frame is being received or transmitted.
A value of 0 indicates that the frame is being received and should
therefore be decrypted; a non-zero value indicates that the frame
is being transmitted
and should be encrypted.
.\"
.Sh IMPLEMENTATION NOTES
The
.Fn ieee80211_wep_crypt
function stores its IV in the interface's embedded
.Vt struct ieee80211com
instance.
.Sh SEE ALSO
.Xr ieee80211 9
.Sh HISTORY
The
.Nm ieee80211
series of functions first appeared in
.Nx 1.5 ,
and were later ported to
.Fx 4.6
and
.Ox 3.6 .
.Sh AUTHORS
.An -nosplit
This man page was written by
.An Bruce M. Simpson Aq Mt bms@FreeBSD.org
and
.An Darron Broad Aq Mt darron@kewl.org .
