.\" Copyright (c) 2000 Kelly Yancey
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd January 3, 2000
.Dt TVTOHZ 9
.Os
.Sh NAME
.Nm tvtohz
.Nd convert time interval to tick count
.Sh SYNOPSIS
.In sys/time.h
.Ft int
.Fn tvtohz "struct timeval *tv"
.Sh DESCRIPTION
The
.Fn tvtohz
function accepts a single argument
.Fa tv
which specifies the time interval over which to calculate the number
of system ticks that would elapse.
.Sh RETURN VALUES
Returns the integral number of system ticks expected to elapse in the given
interval, including the current tick.
.Sh SEE ALSO
.Xr microtime 9 ,
.Xr microuptime 9 ,
.Xr timeout 9
.Sh HISTORY
The
.Nm
function first appeared in
.Fx 3.0
.Sh AUTHORS
This manual page was written by
.An Kelly Yancey Aq Mt kbyanc@posi.net .
