.\" Copyright (c) 2011 Kai Wang
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id: dwarf_add_AT_producer.3 3640 2018-10-14 14:09:13Z jkoshy $
.\"
.Dd September 4, 2011
.Dt DWARF_ADD_AT_PRODUCER 3
.Os
.Sh NAME
.Nm dwarf_add_AT_producer
.Nd create and attach a DW_AT_producer attribute
.Sh LIBRARY
.Lb libdwarf
.Sh SYNOPSIS
.In libdwarf.h
.Ft Dwarf_P_Attribute
.Fo dwarf_add_AT_producer
.Fa "Dwarf_P_Die die"
.Fa "char *producer"
.Fa "Dwarf_Error *err"
.Fc
.Sh DESCRIPTION
Function
.Fn dwarf_add_AT_producer
creates a
.Dv DW_AT_producer
attribute descriptor and attaches it to the debugging information
entry referenced by argument
.Ar die .
The created attribute will have DWARF form
.Dv DW_FORM_strp .
.Pp
Argument
.Ar die
should reference a debugging information entry allocated using
.Xr dwarf_new_die 3 .
.Pp
Argument
.Ar producer
should point to a NUL-terminated string which will become the value of
the created attribute.
.Pp
If argument
.Ar err
is not NULL, it will be used to store error information in case
of an error.
.Sh RETURN VALUES
On success, function
.Fn dwarf_add_AT_producer
returns the created attribute descriptor.
In case of an error, function
.Fn dwarf_add_AT_producer
returns
.Dv DW_DLV_BADADDR
and sets the argument
.Ar err .
.Sh ERRORS
Function
.Fn dwarf_add_AT_producer
can fail with:
.Bl -tag -width ".Bq Er DW_DLE_ARGUMENT"
.It Bq Er DW_DLE_ARGUMENT
Either of the arguments
.Ar die
or
.Ar producer
was NULL.
.It Bq Er DW_DLE_MEMORY
An out of memory condition was encountered during the execution of
the function.
.El
.Sh SEE ALSO
.Xr dwarf 3 ,
.Xr dwarf_add_AT_comp_dir 3 ,
.Xr dwarf_add_AT_const_value_string 3 ,
.Xr dwarf_add_AT_name 3 ,
.Xr dwarf_add_AT_string 3 ,
.Xr dwarf_new_die 3
