/*
 * Automatically generated C config: don't edit
 * Tue Aug 10 19:52:12 2010
 */

/* OSes supported */
#define WILC_WIN32		0
#define WILC_NU				1
#define WILC_MTK		2
#define WILC_LINUX		3
#define WILC_LINUXKERNEL	4
/* the current OS */
/* #define WILC_PLATFORM WILC_LINUXKERNEL */


/* Logs options */
#define WILC_LOGS_NOTHING          0
#define WILC_LOGS_WARN             1
#define WILC_LOGS_WARN_INFO        2
#define WILC_LOGS_WARN_INFO_DBG    3
#define WILC_LOGS_WARN_INFO_DBG_FN 4
#define WILC_LOGS_ALL              5

#define WILC_LOG_VERBOSITY_LEVEL WILC_LOGS_ALL

/* OS features supported */

#define CONFIG_WILC_THREAD_FEATURE 1
/* #define CONFIG_WILC_THREAD_SUSPEND_CONTROL 1 */
/* #define CONFIG_WILC_THREAD_STRICT_PRIORITY 1 */
#define CONFIG_WILC_SEMAPHORE_FEATURE 1
/* #define CONFIG_WILC_SEMAPHORE_TIMEOUT 1 */
#define CONFIG_WILC_SLEEP_FEATURE 1
#define CONFIG_WILC_SLEEP_HI_RES 1
#define CONFIG_WILC_TIMER_FEATURE 1
/* #define CONFIG_WILC_TIMER_PERIODIC 1 */
#define CONFIG_WILC_MEMORY_FEATURE 1
/* #define CONFIG_WILC_MEMORY_POOLS 1 */
/* #define CONFIG_WILC_MEMORY_DEBUG 1 */
/* #define CONFIG_WILC_ASSERTION_SUPPORT 1 */
#define CONFIG_WILC_STRING_UTILS 1
#define CONFIG_WILC_MSG_QUEUE_FEATURE
/* #define CONFIG_WILC_MSG_QUEUE_IPC_NAME */
/* #define CONFIG_WILC_MSG_QUEUE_TIMEOUT */
/* #define CONFIG_WILC_FILE_OPERATIONS_FEATURE */
/* #define CONFIG_WILC_FILE_OPERATIONS_STRING_API */
/* #define CONFIG_WILC_FILE_OPERATIONS_PATH_API */
#define CONFIG_WILC_TIME_FEATURE
/* #define CONFIG_WILC_EVENT_FEATURE */
/* #define CONFIG_WILC_EVENT_TIMEOUT */
/* #define CONFIG_WILC_SOCKET_FEATURE */
/* #define CONFIG_WILC_MATH_OPERATIONS_FEATURE */
/* #define CONFIG_WILC_EXTENDED_FILE_OPERATIONS */
/* #define CONFIG_WILC_EXTENDED_STRING_OPERATIONS */
/* #define CONFIG_WILC_EXTENDED_TIME_OPERATIONS */
