# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_POWER_SEQUENCING)		+= pwrseq-core.o
pwrseq-core-y				:= core.o

obj-$(CONFIG_POWER_SEQUENCING_QCOM_WCN)	+= pwrseq-qcom-wcn.o
obj-$(CONFIG_POWER_SEQUENCING_TH1520_GPU) += pwrseq-thead-gpu.o
obj-$(CONFIG_POWER_SEQUENCING_PCIE_M2)	+= pwrseq-pcie-m2.o
